/**
 * Mode d'emploi : L'accueil Chantiers, la fiche client, la note vocale, la transcription, Informations et Prix.
 *
 * Chaque fiche se prouve contre le code (`scripts/test-mode-emploi.ts`) : la
 * règle, la recherche et le pourquoi vivent dans `src/lib/mode-emploi.ts`.
 */
import type { FicheModeEmploi } from "../mode-emploi";

const ACCUEIL = "src/app/EcranChantiers.tsx";
const LISTE = "src/app/ListeChantiers.tsx";
const NOTIFS = "src/app/Notifications.tsx";
const SUITE = "src/lib/suite-de-la-reponse.ts";
const FICHE = "src/app/chantiers/nouveau/FormulaireNouveauChantier.tsx";
const DICTER = "src/app/chantiers/nouveau/DicterCoordonnees.tsx";
const ANNEAU = "src/app/chantiers/[id]/AnneauNoteVocale.tsx";
const PELLICULE = "src/app/chantiers/[id]/Pellicule.tsx";
const VISIONNEUSE = "src/components/atlas/VisionneusePhoto.tsx";
const DEVIS_DICTEE = "src/app/chantiers/[id]/DevisDepuisDictee.tsx";
const NOTE = "src/app/chantiers/[id]/note-vocale/NoteVocaleClient.tsx";
const TRANSCRIPTION = "src/app/chantiers/[id]/transcription/page.tsx";
const TEXTE_DICTE = "src/app/chantiers/[id]/transcription/TexteDicte.tsx";
const INFOS_PAGE = "src/app/chantiers/[id]/informations/page.tsx";
const INFOS = "src/app/chantiers/[id]/informations/InformationsClient.tsx";
const BROUILLON = "src/app/chantiers/[id]/informations/BrouillonSection.tsx";
const PRIX = "src/app/chantiers/[id]/prix/PrixClient.tsx";
const PROPOSITION = "src/app/chantiers/[id]/prix/PropositionPrixSection.tsx";

const OU_FICHE_CLIENT = "« Chantiers » dans la barre du bas, « Créer un devis » : écran Fiche client";

/** Le glissement qui retire une ligne, partout où il existe. */
export const FICHE_RETRAIT =
  "Glissez la ligne de droite à gauche, puis appuyez sur « Retirer ». " +
  "La ligne tombe et « Annuler » reste six secondes en bas de l'écran.";

export const FICHES_CHANTIER: FicheModeEmploi[] = [
  // --- L'accueil Chantiers --------------------------------------------------
  {
    id: "chantiers-nouveau",
    ecran: "Chantiers",
    ou: "« Chantiers », dans la barre du bas",
    intitule: "Créer un chantier, un devis",
    motsCles: ["creer", "nouveau", "ajouter", "devis", "chantier", "commencer", "demarrer", "client"],
    geste: "Appuyez sur « Créer un devis », sous le titre « Vos chantiers » : la fiche client monte.",
    reserve: "Quand l'essai est terminé, le bouton est grisé et l'écran dit de choisir une formule.",
    source: ACCUEIL,
    preuves: ["Créer un devis", "Vos chantiers", "lectureSeule"],
    ailleurs: [{ source: "src/lib/abonnements.ts", preuves: ["Choisissez une formule pour créer de nouveau."] }],
  },
  {
    id: "chantiers-fermer-fiche-client",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Refermer la fiche client sans perdre ce qu'on a tapé",
    motsCles: ["fermer", "refermer", "quitter", "sortir", "retour", "revenir", "perdre", "fiche", "client"],
    geste:
      "Touchez la flèche en haut à gauche, ou le haut de l'écran derrière la fiche. " +
      "Ce qui est déjà tapé est enregistré en sortant.",
    source: FICHE,
    preuves: ['aria-label="Retour à la liste des chantiers"', "sortirEnEnregistrant"],
    ailleurs: [{ source: ACCUEIL, preuves: ["onClick={() => feuille.current?.fermer()}"] }],
  },
  {
    id: "chantiers-adresse-manquante",
    ecran: "Chantiers",
    ou: "« Chantiers », dans la barre du bas",
    intitule: "Compléter l'adresse ou les coordonnées d'un chantier depuis la liste",
    motsCles: ["adresse", "renseignee", "manquante", "coordonnees", "completer", "ajouter", "telephone", "modifier"],
    geste: "Touchez « Adresse non renseignée », en rouge sous le nom : la fiche client du chantier s'ouvre.",
    reserve: "Cette mention n'apparaît que sur un chantier sans adresse.",
    source: LISTE,
    preuves: ['data-atlas="lieu-manquant"', "/coordonnees`"],
    ailleurs: [{ source: "src/lib/nom-chantier.ts", preuves: ['LIEU_MANQUANT = "Adresse non renseignée"'] }],
  },
  {
    id: "chantiers-etat-ligne",
    ecran: "Chantiers",
    ou: "« Chantiers », dans la barre du bas",
    intitule: "Savoir où en est un chantier, si le devis est parti",
    motsCles: ["etat", "etape", "statut", "envoye", "relancer", "reponse", "brouillon", "ligne", "savoir"],
    geste:
      "Lisez la ligne en capitales sous l'adresse : « Brouillon », « Devis prêt à envoyer », " +
      "« Devis envoyé, sans réponse », « Devis envoyé, à relancer ». Le jour de l'envoi est écrit dessous.",
    reserve: "Une ligne en or attend un geste de votre part.",
    source: "src/lib/chantier-etat.ts",
    preuves: ['"Devis envoyé, sans réponse"', '"Devis envoyé, à relancer"', 'devis_pret: "Devis prêt à envoyer"', 'brouillon: "Brouillon"'],
    ailleurs: [{ source: LISTE, preuves: ["{c.etat}", "{c.precision}"] }],
    lieu: true,
  },
  // --- Les cartes de l'accueil ----------------------------------------------
  {
    id: "chantiers-carte-correction",
    ecran: "Chantiers",
    ou: "« Chantiers », la carte teintée en haut de la liste",
    intitule: "Le client demande une correction du devis",
    motsCles: ["correction", "corriger", "demandee", "client", "modifier", "devis", "revient", "message"],
    geste: "Sur la carte « Correction demandée », lisez le message du client puis touchez « Corriger le devis ».",
    source: NOTIFS,
    preuves: ['"Correction demandée"', "n.messageClient"],
    ailleurs: [{ source: SUITE, preuves: ['"Corriger le devis"'] }],
  },
  {
    id: "chantiers-carte-accepte",
    ecran: "Chantiers",
    ou: "« Chantiers », la carte en haut de la liste",
    intitule: "Le client a accepté le devis, ou proposé une autre date",
    motsCles: ["accepte", "accepter", "valide", "signe", "date", "proposee", "client", "oui"],
    geste: "Sur la carte « Devis accepté » ou « Autre date proposée », touchez « Ouvrir le devis validé ».",
    source: NOTIFS,
    preuves: ['"Devis accepté"', '"Autre date proposée"'],
    ailleurs: [{ source: SUITE, preuves: ['"Ouvrir le devis validé"'] }],
  },
  {
    id: "chantiers-carte-refuse",
    ecran: "Chantiers",
    ou: "« Chantiers », la carte teintée en haut de la liste",
    intitule: "Le devis est retourné ou caduc, sans réponse du client",
    motsCles: ["retourne", "refuse", "refus", "caduc", "expire", "reponse", "renvoyer", "reprendre"],
    geste: "Sur la carte « Devis retourné » ou « Devis caduc », touchez « Reprendre le devis » pour le renvoyer.",
    source: NOTIFS,
    preuves: ['"Devis retourné"', '"Devis caduc"'],
    ailleurs: [{ source: SUITE, preuves: ['"Reprendre le devis"'] }],
  },
  {
    id: "chantiers-carte-facture-recue",
    ecran: "Chantiers",
    ou: "« Chantiers », la carte en haut de la liste",
    intitule: "Le client a confirmé avoir reçu la facture",
    motsCles: ["recue", "reception", "confirme", "client", "attendent", "paiement"],
    geste: "Sur la carte « Facture reçue », touchez « Voir les factures qui attendent ».",
    source: NOTIFS,
    preuves: ['"Facture reçue"', '"Voir les factures qui attendent"'],
  },
  {
    id: "chantiers-carte-impayee",
    ecran: "Chantiers",
    ou: "« Chantiers », la carte en haut de la liste",
    intitule: "Rappel de facture impayée : dire qu'on a été payé",
    motsCles: ["impayee", "impaye", "paye", "paiement", "echeance", "recu", "retard"],
    geste:
      "Sur la carte « Facture impayée », touchez « J'ai reçu le paiement » ou « J'ai reçu une partie ». " +
      "« J'ai vu » repousse seulement le rappel.",
    reserve: "Ce rappel n'apparaît que s'il est allumé dans Réglages, Notifications.",
    source: NOTIFS,
    preuves: ['"Facture impayée"', "J'ai reçu le paiement", "J'ai reçu une partie", "repousserRappelFactureAction"],
  },
  {
    id: "chantiers-carte-rappels",
    ecran: "Chantiers",
    ou: "« Chantiers », la carte en haut de la liste",
    intitule: "Rappels : devis en attente, devis sans réponse, chantier à facturer",
    motsCles: ["rappel", "rappels", "attente", "relance", "relancer", "facturer", "oublie", "reponse"],
    geste:
      "Touchez le lien de la carte : « Faire le devis » sur « Devis en attente », « Ouvrir le chantier » " +
      "sur « Devis sans réponse », « Créer la facture » sur « À facturer ».",
    reserve: "Ces rappels se règlent dans Réglages, Notifications.",
    source: NOTIFS,
    preuves: ["Devis en attente depuis", '"Devis sans réponse"', '"À facturer"', '"Faire le devis"', '"Ouvrir le chantier"', '"Créer la facture"'],
  },
  {
    id: "chantiers-carte-j-ai-vu",
    ecran: "Chantiers",
    ou: "« Chantiers », les cartes en haut de la liste",
    intitule: "Faire disparaître une carte de réponse ou de rappel",
    motsCles: ["carte", "notification", "masquer", "cacher", "disparaitre", "vu", "enlever", "bandeau"],
    geste: "Touchez « J'ai vu » sous la carte.",
    reserve: "Un rappel revient après son délai si rien n'a bougé.",
    source: NOTIFS,
    preuves: ["J&apos;ai vu", 'data-atlas="j-ai-vu"'],
  },
  {
    id: "chantiers-cartes-toutes",
    ecran: "Chantiers",
    ou: "« Chantiers », sous la première carte",
    intitule: "Voir toutes les réponses de clients et les rappels",
    motsCles: ["cartes", "notifications", "autres", "toutes", "regarder", "deplier", "replier", "reponses"],
    geste: "Touchez « autres devis à regarder » sous la carte. « Replier » les range.",
    reserve: "Une seule carte s'affiche d'abord.",
    source: NOTIFS,
    preuves: ["autres devis à regarder", "1 autre devis à regarder", "Replier"],
  },
  // --- La fiche client (création, reprise) ----------------------------------
  {
    id: "nouveau-chantier-saisie",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Renseigner le client d'un nouveau chantier",
    motsCles: ["nouveau", "chantier", "client", "nom", "telephone", "email", "adresse", "saisir", "remplir"],
    geste:
      "Tapez le nom du client, son téléphone, son e-mail et l'adresse du chantier, puis dictez à la note vocale " +
      "ou touchez « Je rédige à la main ».",
    reserve: "Le nom crée la fiche du client. Sans téléphone ni e-mail, le devis ne pourra pas partir.",
    source: FICHE,
    preuves: ["Fiche client", "Nom du client", "Téléphone", "E-mail", '"Adresse du chantier"', "Je rédige à la main"],
  },
  {
    id: "chantier-rediger-main",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Écrire son devis soi-même, sans dicter",
    motsCles: ["rediger", "ecrire", "main", "taper", "manuel", "manuellement", "sans", "dicter", "devis"],
    geste: "Touchez « Je rédige à la main », en bas de la fiche client : le devis s'ouvre, vide.",
    reserve: "Le bouton disparaît pendant qu'on dicte.",
    source: FICHE,
    preuves: ["Je rédige à la main", "!dicteeEnCours"],
  },
  {
    id: "chantier-civilite",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Choisir Monsieur ou Madame pour le client",
    motsCles: ["civilite", "monsieur", "madame", "mme", "titre", "genre", "homme", "femme"],
    geste: "Touchez « Mr » ou « Mme », au-dessus du nom du client.",
    source: "src/components/atlas/ChoixCivilite.tsx",
    preuves: ['"Mr"', '"Mme"'],
    ailleurs: [{ source: FICHE, preuves: ["<ChoixCivilite"] }],
  },
  {
    id: "chantier-adresse-client",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Mettre une adresse du client différente de celle du chantier",
    motsCles: ["adresse", "client", "differente", "domicile", "facturation", "autre", "deux"],
    geste: "Touchez « + Client », à droite de « Chantier » : une seconde case d'adresse s'ouvre.",
    source: FICHE,
    preuves: ["+ Client", '"Adresse du client"'],
  },
  {
    id: "chantier-envoi-canal",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Choisir d'envoyer le devis par SMS ou par e-mail",
    motsCles: ["envoi", "sms", "mail", "email", "canal", "texto", "message", "envoyer"],
    geste: "Sur la ligne « Envoi », touchez « SMS » ou « E-mail ».",
    reserve: "« SMS » ne s'active qu'avec un téléphone tapé, « E-mail » qu'avec une adresse e-mail.",
    source: FICHE,
    preuves: ["Envoi", 'libelle="SMS"', 'libelle="E-mail"', "disponible={aTelephone}"],
  },
  {
    id: "chantier-client-connu",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Reprendre un client déjà connu",
    motsCles: ["client", "connu", "existant", "ancien", "reprendre", "retrouver", "propose", "habitue"],
    geste:
      "Tapez son nom : touchez-le dans la liste qui s'ouvre. Atlas remplit ce qu'il sait. " +
      "Si ce n'est pas le bon, touchez « Ce n'est pas lui ».",
    source: FICHE,
    preuves: ['aria-label="Clients proposés"', "Repris de sa fiche", "Ce n&apos;est pas lui"],
  },
  {
    id: "chantier-dicter-coordonnees",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Dicter le nom, le téléphone et l'adresse du client",
    motsCles: ["dicter", "coordonnees", "micro", "nom", "telephone", "adresse", "parler", "voix", "client"],
    geste: "Touchez le petit micro en haut à droite, dites les coordonnées, puis touchez-le à nouveau.",
    reserve: "Seules les cases vides sont remplies.",
    source: DICTER,
    preuves: ['"Dicter les informations du client"', "J'écoute. Touchez pour arrêter.", '"Arrêter la dictée"'],
  },
  {
    id: "fiche-note-vocale",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Dicter le chantier pour qu'Atlas écrive le devis",
    motsCles: ["dicter", "dictee", "vocal", "vocale", "note", "micro", "parler", "enregistrer", "voix"],
    geste:
      "Touchez le micro au centre, décrivez le chantier, puis touchez l'avion à droite : " +
      "Atlas prépare le devis et l'ouvre.",
    source: ANNEAU,
    preuves: ['aria-label="Dicter une note vocale"', 'aria-label="Envoyer la note et préparer le devis"', "Appuyez et décrivez le chantier"],
    ailleurs: [{ source: FICHE, preuves: ["<AnneauNoteVocale"] }],
  },
  {
    id: "chantier-dictee-jeter",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Jeter une dictée en cours pour recommencer",
    motsCles: ["jeter", "poubelle", "annuler", "recommencer", "dictee", "effacer", "supprimer", "rate"],
    geste: "Pendant la dictée, touchez la poubelle à gauche du chrono.",
    source: ANNEAU,
    preuves: ['aria-label="Supprimer la note"'],
  },
  {
    id: "chantier-dictee-retirer",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Retirer une dictée déjà envoyée",
    motsCles: ["retirer", "supprimer", "effacer", "enlever", "dictee", "note", "vocale", "redicter"],
    geste: "Glissez la ligne « Votre dictée » de droite à gauche, puis « Retirer ». Vous pouvez redicter.",
    reserve: "« Annuler » reste quelques secondes pour revenir en arrière.",
    source: FICHE,
    preuves: ["Votre dictée", "LigneRetirable", "retraitDeLaNote"],
  },
  {
    id: "photos-ajouter",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Ajouter des photos au chantier",
    motsCles: ["photo", "photos", "image", "ajouter", "pellicule", "appareil", "prendre", "galerie"],
    geste: "Sous « Photos », touchez le carré « + » puis prenez ou choisissez les photos.",
    reserve: "Au plus 15 photos à la fois, et 30 par chantier.",
    source: PELLICULE,
    preuves: ['"Ajouter des photos"', 'multiple', 'accept={ACCEPT_PHOTOS}'],
    ailleurs: [
      { source: FICHE, preuves: ["Photos", "<Pellicule"] },
      { source: "src/lib/photos-plafonds.ts", preuves: ["PHOTOS_MAX_PAR_CHANTIER = 30", "pellicule: 15"] },
    ],
  },
  {
    id: "chantier-photo-retirer",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Supprimer une photo du chantier",
    motsCles: ["photo", "photos", "supprimer", "retirer", "enlever", "effacer", "virer", "image"],
    geste: "Touchez la photo pour l'ouvrir, puis « Retirer ». « Annuler » reste quelques secondes en dessous.",
    source: PELLICULE,
    preuves: ['aria-label="Retirer cette photo"', "Retirer", "TiroirDesRetires"],
  },
  {
    id: "chantier-photo-voir",
    ecran: "Fiche client",
    ou: OU_FICHE_CLIENT,
    intitule: "Regarder les photos du chantier en grand",
    motsCles: ["photo", "photos", "voir", "agrandir", "grand", "regarder", "suivante", "defiler"],
    geste: "Touchez une photo. Glissez du doigt pour passer à la suivante, touchez la croix pour fermer.",
    source: VISIONNEUSE,
    preuves: ['aria-label="Fermer"', "Photo suivante", "onTouchStart"],
    ailleurs: [{ source: PELLICULE, preuves: ["Voir la photo"] }],
  },
  {
    id: "chantier-photos-derniere-fois",
    ecran: "Fiche client",
    ou: "« Chantiers », « Vos clients », le nom du client, puis « Autre chantier »",
    intitule: "Reprendre les photos du chantier précédent d'un client",
    motsCles: ["photos", "anciennes", "precedent", "derniere", "fois", "reprendre", "client", "ancien"],
    geste: "Sous « La dernière fois », touchez les photos à reprendre : elles s'allument.",
    reserve: "Une photo non touchée ne rejoint pas le nouveau chantier.",
    source: FICHE,
    preuves: ["La dernière fois", "Reprendre une photo de"],
    ailleurs: [{ source: "src/app/clients/[id]/RepartirDeCeClient.tsx", preuves: ["Autre chantier"] }],
  },
  // --- La préparation du devis depuis la dictée -----------------------------
  {
    id: "chantier-devis-sans-prix",
    ecran: "Fiche client",
    ou: "après la dictée, quand Atlas n'a pas pu chiffrer",
    intitule: "Atlas n'a pas trouvé de prix pour la dictée",
    motsCles: ["prix", "chiffrer", "impossible", "manque", "tarif", "duree", "equipe", "poser"],
    geste: "Touchez « Ouvrir le devis et poser les prix », ou « Compléter la durée et l'équipe ».",
    source: DEVIS_DICTEE,
    preuves: ["Ouvrir le devis et poser les prix", "Compléter la durée et l&apos;équipe"],
  },
  {
    id: "chantier-dictee-conflit",
    ecran: "Transcription",
    ou: "après avoir demandé le devis depuis la dictée",
    intitule: "Refaire le devis depuis la dictée alors qu'on l'a corrigé",
    motsCles: ["corrections", "repartir", "dictee", "conserver", "ecraser", "garder", "refaire"],
    geste: "Touchez « Conserver mes corrections » pour garder le devis, ou « Repartir de la dictée » pour le refaire.",
    reserve: "Repartir de la dictée efface vos corrections.",
    source: DEVIS_DICTEE,
    preuves: ["Conserver mes corrections", "Repartir de la dictée"],
  },
  // --- Écran Note vocale ----------------------------------------------------
  {
    id: "note-vocale-ou",
    ecran: "Note vocale",
    ou: "« Chantiers » dans la barre du bas, puis le chantier : écran Transcription ou Informations",
    intitule: "Ouvrir l'écran de la note vocale d'un chantier",
    motsCles: ["note", "vocale", "ecran", "ouvrir", "trouver", "sont", "enregistrement"],
    geste: "Sur l'écran Transcription ou Informations du chantier, touchez « Aller à la note vocale ».",
    reserve: "Ce lien n'apparaît que tant que la dictée n'est pas transcrite.",
    source: TRANSCRIPTION,
    preuves: ["Aller à la note vocale", "/note-vocale`"],
    ailleurs: [{ source: BROUILLON, preuves: ["Aller à la note vocale"] }],
    lieu: true,
  },
  {
    id: "note-vocale-enregistrer",
    ecran: "Note vocale",
    ou: "l'écran Note vocale d'un chantier",
    intitule: "Enregistrer une note vocale sur l'écran Note vocale",
    motsCles: ["enregistrer", "enregistrement", "arreter", "stop", "note", "vocale"],
    geste: "Touchez « Enregistrer une note vocale », parlez, puis « Arrêter l'enregistrement ».",
    source: NOTE,
    preuves: ["Enregistrer une note vocale", "Arrêter l&apos;enregistrement"],
  },
  {
    id: "note-vocale-ecouter",
    ecran: "Note vocale",
    ou: "l'écran Note vocale d'un chantier",
    intitule: "Réécouter sa note vocale",
    motsCles: ["ecouter", "reecouter", "lire", "entendre", "note", "vocale", "audio", "play"],
    geste: "Touchez le rond de lecture à gauche de la note. Touchez-le à nouveau pour la pause.",
    reserve: "Une fois transcrit, l'audio est effacé : l'écran dit « Enregistrement effacé » et le texte reste.",
    source: NOTE,
    preuves: ['"Écouter la note"', '"Mettre en pause"', "Enregistrement effacé"],
  },
  {
    id: "note-vocale-retirer",
    ecran: "Note vocale",
    ou: "l'écran Note vocale d'un chantier",
    intitule: "Supprimer la note vocale",
    motsCles: ["supprimer", "retirer", "effacer", "enlever", "note", "vocale", "virer"],
    geste: "Glissez la note de droite à gauche, puis « Retirer ».",
    reserve: "« Annuler » reste quelques secondes en bas de l'écran.",
    source: NOTE,
    preuves: ["LigneRetirable", 'libelle="cette note vocale"', "TiroirDesRetires"],
  },
  {
    id: "note-vocale-transcrire",
    ecran: "Note vocale",
    ou: "l'écran Note vocale d'un chantier",
    intitule: "Lancer ou relancer la transcription d'une note",
    motsCles: ["transcription", "transcrire", "lancer", "relancer", "reessayer", "note"],
    geste: "Touchez « Lancer la transcription ». Si elle échoue, touchez « Réessayer ».",
    source: NOTE,
    preuves: ["Lancer la transcription", "Réessayer"],
  },
  {
    id: "note-vocale-suite",
    ecran: "Note vocale",
    ou: "l'écran Note vocale d'un chantier",
    intitule: "Passer de la note vocale au devis",
    motsCles: ["devis", "creer", "dictee", "suite", "continuer", "main", "texte"],
    geste:
      "Touchez « Créer le devis à partir de ma dictée ». « voir le texte » ouvre la transcription, " +
      "« Ou rédiger le devis à la main » ouvre le devis vide.",
    reserve: "Le bouton du devis n'apparaît qu'une fois la transcription faite.",
    source: NOTE,
    preuves: ["voir le texte", "Ou rédiger le devis à la main", "<DevisDepuisDictee"],
    ailleurs: [{ source: DEVIS_DICTEE, preuves: ["Créer le devis à partir de ma dictée"] }],
  },
  // --- Écran Transcription --------------------------------------------------
  {
    id: "transcription-ou",
    ecran: "Transcription",
    ou: "« Chantiers » dans la barre du bas, puis le chantier : écran Informations",
    intitule: "Relire le texte de sa dictée",
    motsCles: ["transcription", "texte", "relire", "lire", "dictee", "voir", "entendu", "sont"],
    geste: "Sur l'écran Informations du chantier, touchez « Voir la transcription ».",
    reserve: "Ce lien n'apparaît qu'une fois la dictée transcrite.",
    source: INFOS_PAGE,
    preuves: ["Voir la transcription"],
    ailleurs: [{ source: TRANSCRIPTION, preuves: ['titre="Transcription"'] }],
    lieu: true,
  },
  {
    id: "transcription-suite",
    ecran: "Transcription",
    ou: "l'écran Transcription d'un chantier",
    intitule: "Passer de la transcription au devis ou aux informations",
    motsCles: ["devis", "creer", "dictee", "informations", "verifier", "suite", "continuer"],
    geste:
      "Touchez « Créer le devis à partir de ma dictée », ou « Ou vérifier les informations une par une ».",
    source: TRANSCRIPTION,
    preuves: ["Ou vérifier les informations une par une", "<DevisDepuisDictee"],
    ailleurs: [{ source: DEVIS_DICTEE, preuves: ["Créer le devis à partir de ma dictée"] }],
  },
  {
    id: "transcription-echec",
    ecran: "Transcription",
    ou: "l'écran Transcription d'un chantier",
    intitule: "La dictée n'a pas été transcrite",
    motsCles: ["echec", "echoue", "transcription", "transcrite", "rate", "marche", "ecrire", "dictee"],
    geste:
      "Touchez « Relancer depuis la note vocale », ou « Écrire ce que j'ai dit » et tapez-le, " +
      "puis « Enregistrer le texte ».",
    reserve: "L'enregistrement reste intact.",
    source: TRANSCRIPTION,
    preuves: ["Relancer depuis la note vocale", 'libelleFerme="Écrire ce que j\'ai dit"'],
    ailleurs: [{ source: TEXTE_DICTE, preuves: ["Enregistrer le texte", "Continuer vers les informations"] }],
  },
  // --- Écran Informations ---------------------------------------------------
  {
    id: "informations-brouillon-generer",
    ecran: "Informations",
    ou: "l'écran Informations d'un chantier",
    intitule: "Tirer les prestations de la dictée",
    motsCles: ["brouillon", "generer", "dictee", "extraire", "analyser", "prestations", "automatique"],
    geste: "Touchez « Générer le brouillon » : Atlas range la dictée en prestations, durée, équipe, matériel.",
    reserve: "Il faut une dictée transcrite.",
    source: BROUILLON,
    preuves: ["Générer le brouillon"],
  },
  {
    id: "informations-brouillon-confirmer",
    ecran: "Informations",
    ou: "l'écran Informations, sous « Entendu »",
    intitule: "Corriger puis confirmer ce qu'Atlas a entendu",
    motsCles: ["confirmer", "brouillon", "entendu", "corriger", "ajouter", "chantier", "regenerer", "croix"],
    geste:
      "Corrigez les cases, retirez une ligne avec sa croix, puis touchez « Confirmer et ajouter au chantier ». " +
      "« Régénérer depuis la dictée » refait l'analyse.",
    reserve: "Tant que ce n'est pas confirmé, les cases du chantier restent cachées.",
    source: BROUILLON,
    preuves: ["Entendu", "Confirmer et ajouter au chantier", "Régénérer depuis la dictée", "aria-label={`Retirer ${ligne.libelle}`}"],
  },
  {
    id: "informations-brouillon-conflit",
    ecran: "Informations",
    ou: "l'écran Informations d'un chantier",
    intitule: "Garder ses corrections quand Atlas propose une nouvelle analyse",
    motsCles: ["remplacer", "corrections", "analyse", "nouvelle", "conserver", "garder", "brouillon"],
    geste: "Touchez « Conserver mes corrections », ou « Remplacer par la nouvelle analyse ».",
    reserve: "Remplacer efface vos corrections.",
    source: BROUILLON,
    preuves: ["Remplacer vos corrections ?", "Conserver mes corrections", "Remplacer par la nouvelle analyse"],
  },
  {
    id: "informations-a-la-main",
    ecran: "Informations",
    ou: "l'écran Informations d'un chantier",
    intitule: "Écrire les informations soi-même sans confirmer la dictée",
    motsCles: ["main", "ecrire", "lignes", "manuel", "taper", "cases", "informations"],
    geste: "Touchez « Écrire les lignes à la main » : les cases du chantier s'ouvrent.",
    reserve: "Ce lien n'apparaît que tant qu'un brouillon attend d'être confirmé.",
    source: INFOS,
    preuves: ["Écrire les lignes à la main"],
  },
  {
    id: "informations-prestations",
    ecran: "Informations",
    ou: "l'écran Informations d'un chantier",
    intitule: "Ajouter, corriger ou retirer une prestation ou du matériel",
    motsCles: [
      "prestation", "prestations", "materiel", "ajouter", "modifier", "corriger",
      "supprimer", "retirer", "informations", "ligne",
    ],
    geste:
      "Touchez une ligne pour la corriger, « + Ajouter une prestation » ou « + Ajouter un matériel » pour en ajouter. " +
      "Pour en retirer une : glissez de droite à gauche, puis « Retirer ».",
    source: INFOS,
    preuves: ['"+ Ajouter une prestation"', '"+ Ajouter un matériel"', "LigneRetirable", "useRetraits"],
  },
  {
    id: "informations-duree-equipe",
    ecran: "Informations",
    ou: "l'écran Informations d'un chantier",
    intitule: "Changer la durée du chantier ou la taille de l'équipe",
    motsCles: ["duree", "temps", "jours", "equipe", "combien", "hommes", "personnes", "modifier"],
    geste: "Sous « Ce chantier prend », choisissez la durée dans la liste. Sous « Équipe », tapez le nombre.",
    source: INFOS,
    preuves: ['label="Ce chantier prend"', 'label="Équipe"'],
    ailleurs: [{ source: "src/app/chantiers/[id]/BandeDuree.tsx", preuves: ['aria-label="Durée du chantier"'] }],
  },
  {
    id: "informations-notes",
    ecran: "Informations",
    ou: "l'écran Informations, sous le matériel",
    intitule: "Noter les déchets, les contraintes d'accès, les remarques",
    motsCles: ["dechets", "branchages", "acces", "contraintes", "remarques", "remarque", "evacuation", "portail"],
    geste: "Tapez dans « Déchets / branchages », « Contraintes d'accès » ou « Remarques ».",
    reserve: "Ces cases n'apparaissent qu'après un brouillon tiré de la dictée.",
    source: BROUILLON,
    preuves: ['label="Déchets / branchages"', "label=\"Contraintes d'accès\"", 'label="Remarques"'],
  },
  {
    id: "informations-ecrire-devis",
    ecran: "Informations",
    ou: "en bas de l'écran Informations",
    intitule: "Aller directement au devis sans passer par le prix",
    motsCles: ["devis", "ecrire", "directement", "sauter", "passer", "rediger"],
    geste: "Touchez « Écrire le devis », tout en bas.",
    source: INFOS,
    preuves: ["Écrire le devis", "/devis-complet`"],
  },
  // --- Écran Prix -----------------------------------------------------------
  {
    id: "prix-lignes",
    ecran: "Prix",
    ou: "l'écran Prix d'un chantier",
    intitule: "Ajouter, corriger ou retirer une ligne de prix",
    motsCles: ["prix", "ligne", "montant", "tarif", "ajouter", "modifier", "supprimer", "retirer", "euro"],
    geste:
      "Touchez le texte ou le montant d'une ligne pour le changer, « + Ajouter une ligne » pour en créer une. " +
      "Pour la retirer : glissez de droite à gauche, puis « Retirer ».",
    source: PRIX,
    preuves: ["+ Ajouter une ligne", 'aria-label="Montant de la ligne, en euros"', "LigneRetirable", "useRetraits"],
  },
  {
    id: "prix-proposition",
    ecran: "Prix",
    ou: "l'écran Prix, encart « Proposition »",
    intitule: "Reprendre le prix proposé par Atlas",
    motsCles: ["proposition", "propose", "calcul", "tarif", "detail", "ajouter", "recalculer"],
    geste:
      "Touchez « Ajouter au détail ». « Voir le détail » montre le calcul, « Relancer le calcul » le refait.",
    reserve: "Quand plusieurs tarifs conviennent, cochez le bon d'abord.",
    source: PROPOSITION,
    preuves: ["Ajouter au détail", "Voir le détail", "Relancer le calcul", "Plusieurs tarifs possibles", 'name="tarif-candidat"'],
  },
  {
    id: "prix-bloque",
    ecran: "Prix",
    ou: "l'écran Prix d'un chantier",
    intitule: "« Préparer le devis » ne répond pas : une ligne attend son prix",
    motsCles: ["bloque", "grise", "marche", "attend", "montant", "manque", "chiffrer", "tarifs"],
    geste: "Touchez « Poser les montants » : Atlas vous amène à la ligne sans prix. Sans aucune ligne, « Ouvrir mes tarifs ».",
    source: PRIX,
    preuves: ["Poser les montants", "Ouvrir mes tarifs", "attend son prix", "!verdict.possible"],
  },
  // --- Chantiers (l'accueil) ------------------------------------------------
  {
    id: "chantiers-retirer",
    ecran: "Chantiers",
    ou: "« Chantiers », dans la barre du bas",
    intitule: "Retirer un chantier de la liste, devis pas encore écrit",
    motsCles: [
      "supprimer", "retirer", "enlever", "effacer", "virer", "chantier", "client",
      "liste", "accueil", "devis", "redaction", "rediger", "brouillon", "attente",
    ],
    geste: FICHE_RETRAIT,
    reserve:
      "Un chantier déjà facturé ne part pas : sa facture figure au relevé de TVA. " +
      "Le glissement découvre alors le motif à la place du bouton.",
    source: "src/app/EcranChantiers.tsx",
    preuves: ["useRetraits", "ListeChantiers", "TiroirDesRetires"],
  },
  {
    id: "chantiers-annuler-retrait",
    ecran: "Chantiers",
    ou: "n'importe quel écran d'où l'on retire quelque chose",
    intitule: "Annuler une suppression qu'on vient de faire",
    motsCles: ["annuler", "revenir", "restaurer", "recuperer", "erreur", "trompe", "supprimer", "retirer", "ligne", "trop", "vite"],
    geste: "Appuyez sur « Annuler » dans le bandeau du bas. Il reste six secondes.",
    reserve: "Passé ce délai, la suppression est écrite et ne se défait plus.",
    source: "src/components/atlas/useRetraits.ts",
    preuves: ["delaiMs = 6000", "annuler"],
  },
  {
    id: "chantiers-ouvrir",
    ecran: "Chantiers",
    ou: "« Chantiers », dans la barre du bas",
    intitule: "Reprendre un chantier là où on s'est arrêté",
    motsCles: ["ouvrir", "reprendre", "continuer", "chantier", "toucher", "revenir", "etape"],
    geste: "Touchez la ligne : Atlas rouvre l'écran où le travail s'est arrêté, pas la fiche.",
    source: "src/app/ListeChantiers.tsx",
    preuves: ["reprise"],
  },
  {
    id: "note-vocale-completer",
    ecran: "Note vocale",
    ou: "l'écran de la note vocale",
    intitule: "Ajouter quelque chose à une note déjà enregistrée",
    motsCles: ["completer", "ajouter", "oublie", "reprendre", "note", "vocale", "suite"],
    geste: "Appuyez sur « Reprendre, j'avais oublié quelque chose », puis parlez.",
    source: "src/app/chantiers/[id]/note-vocale/NoteVocaleClient.tsx",
    preuves: ["Reprendre, j'avais oublié quelque chose"],
  },
  {
    id: "note-vocale-remplacer",
    ecran: "Note vocale",
    ou: "l'écran de la note vocale",
    intitule: "Refaire une note vocale depuis le début",
    motsCles: ["remplacer", "refaire", "recommencer", "note", "vocale", "effacer", "supprimer"],
    geste: "Appuyez sur « Remplacer la note », confirmez, puis réenregistrez.",
    source: "src/app/chantiers/[id]/note-vocale/NoteVocaleClient.tsx",
    preuves: ["Remplacer la note", "Remplacer cette note vocale ?"],
  },
  {
    id: "note-vocale-fichier",
    ecran: "Note vocale",
    ou: "l'écran de la note vocale",
    intitule: "Envoyer un fichier audio déjà enregistré",
    motsCles: ["fichier", "audio", "importer", "televerser", "memo", "dictaphone", "ajouter"],
    geste: "Appuyez sur « Ajouter un fichier audio » et choisissez l'enregistrement.",
    source: "src/app/chantiers/[id]/note-vocale/NoteVocaleClient.tsx",
    preuves: ["Ajouter un fichier audio"],
  },
  {
    id: "transcription-corriger",
    ecran: "Transcription",
    ou: "l'écran de la transcription, après la dictée",
    intitule: "Corriger le texte qu'Atlas a entendu",
    motsCles: ["corriger", "transcription", "texte", "faute", "modifier", "ecrire", "mal", "compris"],
    geste: "Appuyez sur « Corriger le texte à la main », modifiez, puis « Enregistrer le texte ».",
    source: "src/app/chantiers/[id]/transcription/TexteDicte.tsx",
    preuves: ["Corriger le texte à la main", "Enregistrer le texte"],
  },
  {
    id: "informations-valider",
    ecran: "Informations",
    ou: "en bas de l'écran Informations",
    intitule: "Passer des informations au prix",
    motsCles: ["valider", "prix", "calculer", "suite", "continuer", "informations", "etape"],
    geste: "Appuyez sur « Valider et calculer le prix ».",
    source: "src/app/chantiers/[id]/informations/InformationsClient.tsx",
    preuves: ["Valider et calculer le prix"],
  },
  {
    id: "prix-preparer-devis",
    ecran: "Prix",
    ou: "en bas de l'écran Prix",
    intitule: "Passer du prix au devis",
    motsCles: ["preparer", "devis", "prix", "continuer", "suite", "generer"],
    geste: "Appuyez sur « Préparer le devis ».",
    source: "src/app/chantiers/[id]/prix/PrixClient.tsx",
    preuves: ["Préparer le devis"],
  },
];
