/**
 * Mode d'emploi : Le devis complet, son envoi, le devis parti, et ce que le client voit sur sa page.
 *
 * Chaque fiche se prouve contre le code (`scripts/test-mode-emploi.ts`) : la
 * règle, la recherche et le pourquoi vivent dans `src/lib/mode-emploi.ts`.
 */
import type { FicheModeEmploi } from "../mode-emploi";
import { FICHE_RETRAIT } from "./chantier";

const DC = "src/app/chantiers/[id]/devis-complet/DevisCompletClient.tsx";
const ENVOI = "src/app/chantiers/[id]/export/EnvoiAuClient.tsx";
const PARTI = "src/app/chantiers/[id]/export/ExportClient.tsx";
const TRANSMETTRE = "src/app/chantiers/[id]/export/TransmettreAuClient.tsx";
const PUBLIC = "src/app/devis/[jeton]/formulaire.tsx";
const PUBLIC_PAGE = "src/app/devis/[jeton]/page.tsx";

export const FICHES_DEVIS: FicheModeEmploi[] = [
  // --- Récritures ------------------------------------------------------------
  {
    id: "devis-tva",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous le Total HT",
    intitule: "Changer le taux de TVA d'un devis",
    motsCles: ["tva", "taux", "10", "20", "5", "changer", "modifier"],
    geste: "Touchez le chiffre entre parenthèses sur la ligne « TVA » sous le total, puis tapez le taux.",
    reserve:
      "Avec plusieurs TVA sur le devis, le taux se change dans le titre de chaque catégorie, au-dessus de ses lignes.",
    source: DC,
    preuves: ['aria-label="Taux de TVA"', "Taux de TVA de la catégorie"],
  },
  {
    id: "devis-dates",
    ecran: "Devis",
    ou: "un chantier, écran Devis, bouton « Choisir la date » en bas",
    intitule: "Proposer une ou deux dates d'intervention au client",
    motsCles: ["date", "dates", "proposer", "intervention", "calendrier", "jour", "choisir", "client"],
    geste:
      "Appuyez sur « Choisir la date », puis touchez le jour voulu dans le calendrier. " +
      "Atlas pose déjà le premier jour libre : touchez un autre jour pour le remplacer.",
    reserve: "Le client ne verra que la date, jamais la demi-journée.",
    source: ENVOI,
    preuves: ["Proposez une ou deux dates", "Ce chantier prend"],
    ailleurs: [{ source: DC, preuves: ["Choisir la date"] }],
  },
  {
    id: "devis-envoyer",
    ecran: "Devis",
    ou: "un chantier, écran Devis, bouton « Choisir la date » en bas",
    intitule: "Envoyer le devis au client",
    motsCles: ["envoyer", "envoi", "devis", "client", "sms", "mail", "email", "transmettre"],
    geste:
      "Appuyez sur « Choisir la date », touchez la date, puis « Envoyer le devis ». " +
      "Votre messagerie s'ouvre avec le message tout prêt : c'est vous qui l'envoyez.",
    reserve:
      "Tant qu'une ligne est à chiffrer, « Choisir la date » est remplacé par « Poser le prix ». " +
      "Si la messagerie ne s'ouvre pas, rouvrez le chantier et appuyez sur « Relancer par SMS » ou « Relancer par e-mail ».",
    source: ENVOI,
    preuves: ["Envoyer le devis", "Par SMS", "Par e-mail"],
    ailleurs: [
      { source: DC, preuves: ["Choisir la date", '"Poser le prix"', "ouvrirLaMessagerie"] },
      { source: TRANSMETTRE, preuves: ['relance: "Relancer par SMS"', 'relance: "Relancer par e-mail"'] },
    ],
  },
  {
    id: "devis-corriger-envoye",
    ecran: "Devis",
    ou: "un chantier dont le devis est parti, écran Devis",
    intitule: "Modifier un devis déjà envoyé",
    motsCles: ["corriger", "modifier", "devis", "envoye", "parti", "erreur", "renvoyer", "changer"],
    geste:
      "Appuyez sur « Modifier mon devis » sous le montant, puis « Modifier quand même ». " +
      "Corrigez, puis renvoyez avec « Choisir la date ».",
    reserve:
      "Tant que vous n'avez pas renvoyé, le client voit l'ancienne version et peut l'accepter au prix d'avant.",
    source: PARTI,
    preuves: ["Modifier mon devis", "Modifier quand même", "Ce devis est chez votre client"],
  },
  {
    id: "devis-telecharger",
    ecran: "Devis",
    ou: "un chantier dont le devis est parti, écran Devis, en bas",
    intitule: "Télécharger le PDF d'un devis envoyé",
    motsCles: ["telecharger", "pdf", "devis", "garder", "enregistrer", "fichier", "imprimer"],
    geste: "Appuyez sur « Télécharger le PDF » en bas de l'écran.",
    reserve:
      "Le bouton n'apparaît qu'une fois le client a répondu ou le lien expiré. " +
      "Avant, le PDF est dans « Vos clients », sur le nom du client, onglet « Devis ».",
    source: PARTI,
    preuves: ["Télécharger le PDF", "!transmission"],
    ailleurs: [{ source: "src/app/clients/[id]/page.tsx", preuves: ['libelle: "Devis"'] }],
  },
  // --- Le devis complet : les lignes ---------------------------------------
  {
    id: "devis-ligne-ajouter",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous les lignes",
    intitule: "Ajouter une ligne au devis",
    motsCles: ["ajouter", "ligne", "nouvelle", "prestation", "rajouter", "article", "poste"],
    geste: "Appuyez sur « + Ajouter une ligne » sous les lignes, puis écrivez la description, la quantité et le prix.",
    reserve: "Avec plusieurs TVA, chaque catégorie a son bouton : la ligne arrive dans celle où vous appuyez.",
    source: DC,
    preuves: ["+ Ajouter une ligne"],
  },
  {
    id: "devis-ligne-modifier",
    ecran: "Devis",
    ou: "un chantier, écran Devis",
    intitule: "Corriger la description, la quantité ou le prix d'une ligne",
    motsCles: ["modifier", "corriger", "ligne", "quantite", "prix", "unitaire", "description", "libelle", "changer"],
    geste: "Touchez directement la description, la quantité ou le prix unitaire et tapez : le montant se recalcule.",
    reserve: "Un devis déjà parti ne se modifie plus : voir « Modifier un devis déjà envoyé ».",
    source: DC,
    preuves: ["Prix unitaire HT", "Montant HT", "Ex : Élagage d'un tilleul"],
  },
  {
    id: "devis-unite",
    ecran: "Devis",
    ou: "un chantier, écran Devis, case Unité d'une ligne",
    intitule: "Choisir l'unité d'une ligne : mètre, m², heure, forfait",
    motsCles: ["unite", "ml", "m2", "m3", "metre", "kg", "heure", "forfait"],
    geste: "Touchez la case « Unité » de la ligne, puis une pastille : u, ml, m², m³, kg, h ou forfait. Vous pouvez aussi l'écrire.",
    source: "src/app/chantiers/[id]/devis-complet/ChampUnite.tsx",
    preuves: ['UNITES_USUELLES = ["u", "ml", "m²", "m³", "kg", "h", "forfait"]'],
    ailleurs: [{ source: DC, preuves: ['<Cellule libelle="Unité">'] }],
  },
  {
    id: "devis-a-chiffrer",
    ecran: "Devis",
    ou: "un chantier, écran Devis, en bas",
    intitule: "Poser le prix d'une ligne marquée à chiffrer",
    motsCles: ["chiffrer", "prix", "manque", "manquant", "vide", "poser", "bloque", "disparu", "grise"],
    geste: "Appuyez sur « Poser le prix » en bas du devis : Atlas vous amène sur la case du prix qui manque.",
    reserve: "Tant qu'une ligne est à chiffrer, le devis ne peut pas partir.",
    source: DC,
    preuves: ["à chiffrer", '"Poser le prix"', '"Poser les prix"'],
  },
  {
    id: "devis-reprendre-prix",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous une ligne",
    intitule: "Reprendre le prix d'un chantier comparable",
    motsCles: ["reprendre", "prix", "dernier", "comparable", "habitude", "rappel", "ancien", "derniere", "fois"],
    geste: "Sous la ligne, appuyez sur « Reprendre ce prix ».",
    reserve: "Ne s'affiche que si Atlas connaît un travail comparable sur un autre chantier.",
    source: DC,
    preuves: ["Reprendre ce prix"],
  },
  {
    id: "devis-titre",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous le mot DEVIS",
    intitule: "Donner un titre au devis",
    motsCles: ["titre", "nommer", "nom", "objet", "intitule", "entete"],
    geste: "Touchez « Titre (optionnel) » sous le mot DEVIS et écrivez.",
    source: DC,
    preuves: ["Titre (optionnel)"],
  },
  // --- Le devis complet : TVA, main d'œuvre, acompte, remise ---------------
  {
    id: "devis-plusieurs-tva",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous les lignes",
    intitule: "Mettre deux taux de TVA sur un même devis",
    motsCles: ["tva", "deux", "plusieurs", "taux", "categorie", "ajouter", "mixte"],
    geste: "Appuyez sur « + Ajouter une TVA » : une catégorie s'ouvre, touchez son taux pour le changer.",
    source: DC,
    preuves: ["+ Ajouter une TVA", "Taux de TVA de la catégorie"],
  },
  {
    id: "devis-ligne-changer-tva",
    ecran: "Devis",
    ou: "un chantier, écran Devis",
    intitule: "Passer une ligne d'une TVA à l'autre",
    motsCles: ["deplacer", "ligne", "tva", "changer", "categorie", "passer", "bouger"],
    geste: "Gardez le doigt appuyé sur la ligne, puis choisissez « Vers la TVA » voulue, ou « Vers une TVA » pour en créer une.",
    reserve: "L'appui long ne marche que si le devis a déjà deux TVA, et pas sur un devis parti.",
    source: DC,
    preuves: ["Déplacer cette ligne", "Vers la ", "Vers une ", "appuiLong"],
  },
  {
    id: "devis-retirer-tva",
    ecran: "Devis",
    ou: "un chantier, écran Devis, titre d'une catégorie de TVA",
    intitule: "Retirer une catégorie de TVA",
    motsCles: ["retirer", "supprimer", "enlever", "tva", "categorie", "taux"],
    geste: "Appuyez sur le « − » à droite du titre de la catégorie : ses lignes reviennent dans la TVA principale.",
    reserve: "La première catégorie n'a pas de « − ».",
    source: DC,
    preuves: ["Retirer la TVA à"],
  },
  {
    id: "devis-main-doeuvre",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous les lignes",
    intitule: "Indiquer la part de main d'œuvre",
    motsCles: ["main", "oeuvre", "doeuvre", "credit", "impot", "services", "personne", "part"],
    geste: "Appuyez sur « + Main d’œuvre », puis tapez le montant sur la ligne « dont main d’œuvre HT ». Le « − » devant la retire.",
    source: DC,
    preuves: ["+ Main d’œuvre"],
    ailleurs: [
      { source: "src/app/chantiers/[id]/devis-complet/LigneMainDoeuvre.tsx", preuves: ["Retirer la main d’œuvre"] },
      { source: "src/lib/main-doeuvre-devis.ts", preuves: ["dont main d’œuvre HT"] },
    ],
  },
  {
    id: "devis-acompte",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous le Total TTC",
    intitule: "Demander un acompte sur le devis",
    motsCles: ["acompte", "avance", "arrhes", "paiement", "echeance", "pourcentage", "commande"],
    geste: "Appuyez sur « + Ajouter un acompte », puis touchez le pourcentage pour le changer. Le « − » devant l'acompte le retire.",
    reserve: "Le reste à régler se calcule sous les acomptes. Le bouton disparaît quand il n'y a plus d'acompte à poser.",
    source: DC,
    preuves: ["+ Ajouter un acompte"],
    ailleurs: [
      { source: "src/app/chantiers/[id]/devis-complet/LigneAcompte.tsx", preuves: ["Retirer l'acompte "] },
      { source: "src/lib/acomptes-devis.ts", preuves: ["Reste à régler après acompte"] },
    ],
  },
  {
    id: "devis-remise-retirer",
    ecran: "Devis et facture",
    ou: "sous le Total HT, ligne « Remise de »",
    intitule: "Enlever la remise accordée",
    motsCles: ["remise", "reduction", "rabais", "retirer", "enlever", "supprimer", "annuler"],
    geste: "Appuyez sur le « − » devant « Remise de ».",
    reserve: "La ligne tombe et « Annuler » reste quelques secondes en bas pour la remettre.",
    source: "src/components/atlas/Remise.tsx",
    preuves: ["Retirer la ${LIBELLE_REDUCTION", "} de"],
    ailleurs: [{ source: DC, preuves: ["retraits.retirer(CLE_REDUCTION"] }],
  },
  // --- Le devis complet : les coordonnées -----------------------------------
  {
    id: "devis-client-coordonnees",
    ecran: "Devis",
    ou: "un chantier, écran Devis, bloc Client",
    intitule: "Corriger le nom, l'adresse, l'e-mail ou le téléphone du client sur le devis",
    motsCles: ["client", "nom", "adresse", "telephone", "mail", "email", "corriger", "coordonnees"],
    geste: "Touchez la case du client sur le devis et corrigez.",
    reserve: "La correction s'enregistre aussi sur la fiche du client. La civilité ne se change pas sur le devis.",
    source: DC,
    preuves: ['aria="Nom du client"', 'aria="Adresse du client"', 'aria="E-mail du client"', 'aria="Téléphone du client"'],
  },
  {
    id: "devis-sans-client",
    ecran: "Devis",
    ou: "un chantier, écran Devis, bloc Client",
    intitule: "Rattacher un client à un devis qui n'en a pas",
    motsCles: ["client", "rattacher", "aucun", "manque", "fiche", "renseigner", "ajouter", "mettre", "sans", "devis"],
    geste: "Sous « Aucun client rattaché à ce chantier. », appuyez sur « Renseigner la fiche client ».",
    source: DC,
    preuves: ["Aucun client rattaché à ce chantier.", "Renseigner la fiche client"],
  },
  {
    id: "devis-adresse-chantier",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous Chantier",
    intitule: "Corriger l'adresse des travaux sur le devis",
    motsCles: ["adresse", "travaux", "chantier", "lieu", "intervention", "corriger"],
    geste: "Touchez l'adresse sous « Chantier » et corrigez.",
    reserve: "Elle ne s'affiche que si elle diffère de l'adresse du client, ou s'il n'y a pas de client.",
    source: DC,
    preuves: ["Adresse des travaux", "<Intertitre>Chantier</Intertitre>"],
  },
  {
    id: "devis-entreprise",
    ecran: "Devis",
    ou: "un chantier, écran Devis, en haut à gauche",
    intitule: "Corriger le nom, l'adresse, le SIRET de mon entreprise sur le devis",
    motsCles: ["entreprise", "siret", "siren", "societe", "entete", "emetteur", "coordonnees"],
    geste: "Touchez le nom, l'adresse, le téléphone, l'e-mail ou le SIRET en haut du devis et corrigez.",
    reserve: "La correction vaut aussi pour vos prochains devis et factures.",
    source: DC,
    preuves: ['placeholder="Votre entreprise"', "N° SIREN / SIRET", "majEmetteurAction"],
  },
  {
    id: "devis-iban",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous Modalités de paiement",
    intitule: "Mettre mon IBAN sur le devis",
    motsCles: ["iban", "rib", "virement", "banque", "bancaire", "paiement"],
    geste: "Sous « Modalités de paiement », touchez « IBAN : FR76 … » et tapez-le.",
    reserve: "Il reste enregistré pour vos prochains devis.",
    source: DC,
    preuves: ["Modalités de paiement", 'placeholder="IBAN : FR76 …"'],
  },
  {
    id: "devis-notes",
    ecran: "Devis",
    ou: "un chantier, écran Devis, sous les totaux",
    intitule: "Ajouter une note ou des conditions sur le devis",
    motsCles: ["note", "notes", "conditions", "remarque", "acces", "mention", "commentaire"],
    geste: "Touchez la zone sous « Notes / conditions » et écrivez.",
    source: DC,
    preuves: ["Notes / conditions"],
  },
  // --- Dicter dans le devis, préparation ------------------------------------
  {
    id: "devis-dicter",
    ecran: "Devis",
    ou: "un chantier, écran Devis, le micro en haut à droite",
    intitule: "Corriger le devis à la voix",
    motsCles: ["dicter", "voix", "micro", "parler", "vocal", "dictee", "oral", "correction", "corriger", "devis"],
    geste:
      "Touchez le micro, parlez, puis touchez-le à nouveau. Décochez ce qui ne va pas, " +
      "puis « Appliquer ce changement », ou « Ne rien changer ».",
    reserve: "Le micro n'est pas là sur un devis déjà parti.",
    source: "src/app/chantiers/[id]/devis-complet/DicterDansLeDevis.tsx",
    preuves: ["Dicter dans le devis", "J'écoute. Touchez pour arrêter.", "Appliquer ce changement", "Ne rien changer"],
    ailleurs: [{ source: DC, preuves: ["!fige && <DicterDansLeDevis"] }],
  },
  {
    id: "devis-questions-chiffrage",
    ecran: "Devis",
    ou: "l'encadré « Avant de chiffrer », pendant qu'Atlas prépare le devis",
    intitule: "Répondre aux questions d'Atlas avant le chiffrage",
    motsCles: ["questions", "chiffrer", "avant", "repondre", "preparation", "precision"],
    geste:
      "Touchez une réponse sous chaque question, puis « Continuer vers le devis ». " +
      "Pour passer outre : « Continuer sans répondre à tout ».",
    reserve: "Ces questions n'apparaissent que quand la dictée ne suffit pas pour chiffrer.",
    source: "src/app/chantiers/[id]/DevisDepuisDictee.tsx",
    preuves: ["Avant de chiffrer", "Continuer vers le devis", "Continuer sans répondre à tout", "Revenir en arrière"],
  },
  // --- Le devis figé --------------------------------------------------------
  {
    id: "devis-fige",
    ecran: "Devis",
    ou: "un devis déjà parti, ouvert en entier",
    intitule: "Le devis ne se modifie plus, que faire",
    motsCles: ["bloque", "fige", "modifie", "plus", "grise", "impossible", "verrouille"],
    geste: "Appuyez sur « Le corriger et le renvoyer » sous le bandeau en haut du devis.",
    reserve: "Si aucun lien n'est parti au client, le lien s'appelle « Reprendre et envoyer ».",
    source: DC,
    preuves: ["Ce devis est parti chez votre client : il ne se modifie plus.", "Le corriger et le renvoyer", "Reprendre et envoyer"],
  },
  // --- La feuille d'envoi ---------------------------------------------------
  {
    id: "devis-deux-dates",
    ecran: "Devis",
    ou: "après « Choisir la date », sous le calendrier",
    intitule: "Proposer deux dates au choix du client",
    motsCles: ["deux", "dates", "choix", "seconde", "deuxieme", "proposition", "alternative"],
    geste: "Allumez « Vous proposez deux dates », puis touchez le premier jour de la deuxième proposition.",
    source: ENVOI,
    preuves: ["Vous proposez deux dates", "Touchez le premier jour de la 2e proposition"],
  },
  {
    id: "devis-autre-date-client",
    ecran: "Devis",
    ou: "après « Choisir la date », sous le calendrier",
    intitule: "Laisser ou non le client proposer une autre date",
    motsCles: ["client", "autre", "date", "libre", "choisir", "autoriser", "laisser"],
    geste: "Allumez ou éteignez « Votre client peut proposer une autre date ».",
    reserve: "Allumé, il ne voit que vos jours libres. Éteint, il choisit parmi vos dates ou demande une correction.",
    source: ENVOI,
    preuves: ["Votre client peut proposer une autre date", "Il ne verra que vos jours libres."],
  },
  {
    id: "devis-duree-envoi",
    ecran: "Devis",
    ou: "après « Choisir la date », en haut de la feuille",
    intitule: "Changer la durée du chantier avant d'envoyer",
    motsCles: ["duree", "jours", "longtemps", "combien", "temps", "changer", "demi"],
    geste: "Appuyez sur « changer » à côté de la durée, puis choisissez sous « Ce chantier prend ».",
    source: ENVOI,
    preuves: ["changer", 'label="Ce chantier prend"'],
  },
  {
    id: "devis-jour-libre",
    ecran: "Devis",
    ou: "après « Choisir la date », dans le calendrier",
    intitule: "Voir si l'équipe est libre un jour donné",
    motsCles: ["libre", "occupe", "disponible", "dispo", "place", "matin", "apres", "planning"],
    geste: "Touchez le jour : dessous, Atlas montre le matin et l'après-midi de votre planning.",
    reserve: "Si le jour ne va pas, Atlas propose un autre jour : appuyez sur « Proposer le » jour indiqué.",
    source: ENVOI,
    preuves: ["JourneeRegardee", "Proposer le "],
    ailleurs: [{ source: "src/app/chantiers/[id]/export/JourneeRegardee.tsx", preuves: ['"Matin"', '"Après-midi"'] }],
  },
  {
    id: "devis-date-effacer",
    ecran: "Devis",
    ou: "après « Choisir la date », sous le calendrier",
    intitule: "Enlever ou déplacer un jour proposé",
    motsCles: ["enlever", "effacer", "retirer", "deplacer", "jour", "date", "annuler"],
    geste: "Touchez le jour proposé pour l'effacer, puis le jour que vous voulez à la place.",
    source: ENVOI,
    preuves: ["Touchez un jour du chantier pour l’effacer", "onClick={() => toucherLeJour(jour)}"],
  },
  {
    id: "devis-envoi-coordonnee",
    ecran: "Devis",
    ou: "après « Choisir la date », quand le client n'a ni numéro ni e-mail",
    intitule: "Envoyer à un client sans téléphone ni e-mail enregistré",
    motsCles: ["numero", "telephone", "mail", "email", "manque", "coordonnee", "joindre"],
    geste: "Choisissez « Par SMS » ou « Par e-mail », tapez le numéro ou l'adresse, puis « Enregistrer et continuer ».",
    source: ENVOI,
    preuves: ['titre: "Par SMS"', 'titre: "Par e-mail"', "Enregistrer et continuer"],
  },
  {
    id: "devis-envoi-annuler",
    ecran: "Devis",
    ou: "après « Choisir la date », en bas de la feuille",
    intitule: "Fermer la feuille d'envoi sans rien envoyer",
    motsCles: ["annuler", "fermer", "retour", "envoyer", "pas", "stop"],
    geste: "Appuyez sur « Annuler » sous « Envoyer le devis ».",
    source: ENVOI,
    preuves: ['aria-label="Annuler l’envoi"', "Annuler"],
  },
  // --- Le devis parti ---------------------------------------------------------
  {
    id: "devis-etat",
    ecran: "Devis",
    ou: "« Chantiers » dans la barre du bas, puis le chantier",
    intitule: "Savoir si le client a répondu au devis",
    motsCles: ["repondu", "accepte", "reponse", "signe", "attente", "etat", "refuse", "valide"],
    geste:
      "Touchez le chantier dans « Chantiers » : en haut de l'écran Devis, l'état s'affiche, " +
      "par exemple « En attente de réponse », « Devis accepté » ou « Correction demandée ».",
    source: "src/lib/etat-envoi.ts",
    preuves: ['en_attente: "En attente de réponse"', 'accepte: "Devis accepté"', 'a_corriger: "Correction demandée"', 'retourne: "Devis retourné"', 'caduc: "Devis caduc"'],
    ailleurs: [{ source: PARTI, preuves: ["etatEnvoiLabel[etatEnvoi]"] }],
    lieu: true,
  },
  {
    id: "devis-relancer",
    ecran: "Devis",
    ou: "un chantier dont le devis est parti, écran Devis, en bas",
    intitule: "Relancer le client qui n'a pas répondu",
    motsCles: ["relancer", "relance", "rappeler", "renvoyer", "lien", "nouvelles", "reponse"],
    geste: "Appuyez sur « Relancer par SMS » ou « Relancer par e-mail » : le message s'ouvre avec le lien du devis.",
    reserve: "Le bouton n'est là que tant que le client n'a pas répondu.",
    source: TRANSMETTRE,
    preuves: ['relance: "Relancer par SMS"', 'relance: "Relancer par e-mail"'],
  },
  {
    id: "devis-changer-canal",
    ecran: "Devis",
    ou: "un chantier dont le devis est parti, écran Devis, en bas",
    intitule: "Envoyer par e-mail plutôt que par SMS, ou l'inverse",
    motsCles: ["mail", "email", "sms", "plutot", "changer", "canal", "message"],
    geste: "Appuyez sur « Plutôt par e-mail » ou « Plutôt par SMS ».",
    reserve:
      "S'il manque le numéro ou l'adresse, tapez-le dans la case qui apparaît, puis « Enregistrer et ouvrir le message ».",
    source: TRANSMETTRE,
    preuves: ['bascule: "Plutôt par e-mail"', 'bascule: "Plutôt par SMS"', "Enregistrer et ouvrir le message"],
  },
  {
    id: "devis-correction-demandee",
    ecran: "Devis",
    ou: "un chantier marqué « Correction demandée », écran Devis",
    intitule: "Traiter une correction demandée par le client",
    motsCles: ["correction", "demandee", "client", "message", "erreur", "corriger", "renvoyer"],
    geste: "Lisez le message du client sous l'état, puis appuyez sur « Corriger et renvoyer ».",
    source: PARTI,
    preuves: ['"Corriger et renvoyer"', "messageClient &&"],
    ailleurs: [{ source: "src/lib/etat-envoi.ts", preuves: ['a_corriger: "Correction demandée"'] }],
  },
  {
    id: "devis-reprendre-refuse",
    ecran: "Devis",
    ou: "un chantier dont le devis est retourné ou caduc, écran Devis",
    intitule: "Reprendre un devis refusé ou dont le lien a expiré",
    motsCles: ["refuse", "retourne", "expire", "caduc", "reprendre", "lien", "valable"],
    geste: "Appuyez sur « Reprendre le devis », corrigez si besoin, puis renvoyez avec « Choisir la date ».",
    source: PARTI,
    preuves: ['"Reprendre le devis"', 'etatEnvoi === "caduc"'],
    ailleurs: [{ source: "src/lib/etat-envoi.ts", preuves: ['retourne: "Devis retourné"', 'caduc: "Devis caduc"'] }],
  },
  // --- Ce que voit le client ------------------------------------------------
  {
    id: "devis-client-page",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client, dans son SMS ou son e-mail",
    intitule: "Ce que le client voit quand il ouvre le devis",
    motsCles: ["client", "voit", "recoit", "page", "lien", "affiche", "apercu"],
    geste:
      "Il voit le numéro du devis, le total HT, la TVA et le TTC, les dates proposées, " +
      "et trois boutons : « J'accepte ce devis », « Une correction avant d'accepter » et « Je ne donne pas suite ».",
    source: PUBLIC,
    preuves: ["J'accepte ce devis", "Une correction avant d", "Je ne donne pas suite"],
    ailleurs: [{ source: PUBLIC_PAGE, preuves: ["Devis n° ", "Total TTC", "Télécharger mon devis"] }],
  },
  {
    id: "devis-client-accepter",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client",
    intitule: "Comment le client accepte le devis",
    motsCles: ["accepter", "accepte", "signer", "signature", "valider", "accord", "client"],
    geste: "Le client coche la date qui lui va, puis appuie sur « J'accepte ce devis ».",
    reserve: "Son accord est horodaté et gardé avec le devis. La date est alors retenue dans votre planning.",
    source: PUBLIC,
    preuves: ["J'accepte ce devis", 'name="choixDate"'],
    ailleurs: [{ source: PUBLIC_PAGE, preuves: ["Votre accord est horodaté et conservé avec le devis."] }],
  },
  {
    id: "devis-client-autre-date",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client, sous les dates proposées",
    intitule: "Comment le client propose une autre date",
    motsCles: ["client", "autre", "date", "propose", "convient", "pas", "changer"],
    geste:
      "Le client coche « Cette date ne me convient pas ? Je propose », touche un jour libre, " +
      "puis « Retenir cette date » et « J'accepte ce devis ».",
    reserve: "Seulement si vous avez laissé allumé « Votre client peut proposer une autre date ».",
    source: PUBLIC,
    preuves: ["libelleAutreDate", "libelleRetenir", "envoi.autreDateAutorisee"],
    ailleurs: [{ source: "src/lib/libelle-dates.ts", preuves: ["Cette date ne me convient pas ? Je propose", "Retenir cette date"] }],
  },
  {
    id: "devis-client-correction",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client",
    intitule: "Comment le client demande une correction",
    motsCles: ["client", "correction", "erreur", "corriger", "demande", "message", "modifier"],
    geste: "Le client écrit l'erreur dans la case sous les dates, puis appuie sur « Une correction avant d'accepter ».",
    reserve: "Sans texte écrit, le bouton refuse. Vous lisez son message sur l'écran Devis du chantier.",
    source: PUBLIC,
    preuves: ["Écrivez-la, votre artisan la lira.", "Une correction avant d", "Écrivez d'abord ce qui doit être corrigé."],
  },
  {
    id: "devis-client-refuser",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client",
    intitule: "Comment le client refuse le devis",
    motsCles: ["refuser", "refus", "client", "suite", "non", "decline", "annule"],
    geste: "Le client appuie sur « Je ne donne pas suite », puis « Oui, je ne donne pas suite ».",
    reserve: "Chez vous, le devis passe à « Devis retourné » et peut être repris.",
    source: PUBLIC,
    preuves: ["Je ne donne pas suite", "Oui, je ne donne pas suite", "Revenir au devis"],
  },
  {
    id: "devis-client-telecharger",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client, sous le total",
    intitule: "Comment le client télécharge son devis",
    motsCles: ["client", "telecharger", "pdf", "garder", "imprimer", "copie"],
    geste: "Le client appuie sur « Télécharger mon devis ».",
    reserve: "Le bouton reste là après son acceptation.",
    source: PUBLIC_PAGE,
    preuves: ["Télécharger mon devis", "BoutonTelechargerDevis jeton"],
    ailleurs: [{ source: "src/app/devis/[jeton]/BoutonTelechargerDevis.tsx", preuves: ["Télécharger mon devis"] }],
  },
  {
    id: "devis-client-retractation",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client, sous les dates",
    intitule: "Le délai de rétractation de 14 jours sur une date proche",
    motsCles: ["retractation", "14", "delai", "quatorze", "commencer", "avant", "legal"],
    geste: "Si la date tombe dans ses 14 jours de rétractation, le client coche la case pour demander que les travaux commencent avant.",
    reserve: "La case n'apparaît que pour une date proche.",
    source: PUBLIC,
    preuves: ["Je demande expressément que les travaux commencent avant sa fin.", 'name="demarrageAnticipe"'],
  },
  {
    id: "devis-client-lien-expire",
    ecran: "Page du devis chez le client",
    ou: "le lien reçu par le client",
    intitule: "Le client voit « Ce lien n'est plus valable »",
    motsCles: ["lien", "marche", "valable", "expire", "ouvre", "client", "plus"],
    geste: "Ouvrez le chantier, appuyez sur « Reprendre le devis », puis renvoyez-le avec « Choisir la date ».",
    source: PUBLIC_PAGE,
    preuves: ["Ce lien n'est plus valable"],
    ailleurs: [{ source: PARTI, preuves: ['"Reprendre le devis"'] }],
  },
  {
    id: "devis-ligne-retirer",
    ecran: "Devis",
    ou: "le devis complet d'un chantier",
    intitule: "Retirer une ligne du devis",
    motsCles: ["devis", "ligne", "supprimer", "retirer", "enlever", "effacer"],
    geste: FICHE_RETRAIT,
    reserve: "Un devis déjà parti chez le client ne se modifie plus : il faut le reprendre (voir « Corriger un devis envoyé »).",
    source: "src/app/chantiers/[id]/devis-complet/DevisCompletClient.tsx",
    preuves: ["LigneRetirable", "useRetraits"],
  },
  {
    id: "devis-remise",
    // **Sur la facture AUSSI, depuis le 11 septembre 2026** — sa demande :
    // *« on n'a pas mis la réduction client cliquable comme sur le devis »*. La
    // fiche qui ne nommerait que le devis l'enverrait chercher là où il n'a
    // pas besoin d'aller.
    ecran: "Devis et facture",
    ou: "sous le total",
    intitule: "Faire une remise au client",
    motsCles: [
      "remise",
      "reduction",
      "geste",
      "pourcentage",
      "rabais",
      "prix",
      "accorde",
      "facture",
    ],
    geste: "Appuyez sur « + Remise », puis renseignez le pourcentage.",
    // **La pièce commune, et non plus l'écran du devis** : le geste est monté
    // par les deux écrans depuis qu'il l'a demandé sur la facture. Ancrée sur
    // un seul des deux, cette fiche rougirait au premier déménagement — c'est
    // ce qui vient d'arriver.
    source: "src/components/atlas/Remise.tsx",
    preuves: ["Remise, en pourcentage", "+ {LIBELLE_REDUCTION}"],
  },
  {
    id: "devis-apercu",
    ecran: "Devis",
    ou: "en bas du devis complet",
    intitule: "Voir le devis tel que le client le recevra",
    motsCles: ["apercu", "pdf", "voir", "regarder", "imprimer", "devis", "telecharger"],
    geste: "Appuyez sur « Aperçu du PDF ».",
    source: "src/app/chantiers/[id]/devis-complet/DevisCompletClient.tsx",
    preuves: ["Aperçu du PDF"],
  },
];
