/**
 * Mode d'emploi : Paysage (arrosage, fiche de chantier, diagnostic, fiches de sécurité), les clients et le catalogue.
 *
 * Chaque fiche se prouve contre le code (`scripts/test-mode-emploi.ts`) : la
 * règle, la recherche et le pourquoi vivent dans `src/lib/mode-emploi.ts`.
 */
import type { FicheModeEmploi } from "../mode-emploi";

const ARROSAGE = "src/app/paysage/arrosage/ArrosageClient.tsx";
const DIAG = "src/app/paysage/diagnostic/[id]/page.tsx";
const SECU = "src/app/paysage/fiches-securite/ListeDesFiches.tsx";
const FICHE = "src/app/paysage/fiche/[id]/FicheChantierClient.tsx";
const COMPOSER = "src/app/paysage/fiche/composer/ComposerMaFiche.tsx";
const DOSSIER = "src/app/clients/[id]/page.tsx";
const MOTS = "src/app/catalogue/MesMots.tsx";
const FILTRE = "src/components/atlas/FiltreDeDate.tsx";
const TIROIR = "src/components/atlas/TiroirDesRetires.tsx";

export const FICHES_PAYSAGE: FicheModeEmploi[] = [
  // --- Paysage : l'écran ----------------------------------------------------
  {
    id: "paysage-terrasse-bois",
    ecran: "Paysage",
    ou: "« Paysage » dans la barre du bas",
    intitule: "Calculer une terrasse bois",
    motsCles: ["terrasse", "bois", "lambourdes", "plots", "visserie", "lames", "deck"],
    geste: "« Terrasse bois » est dans « Paysage », marquée « Bientôt » : l'outil n'est pas encore disponible.",
    source: "src/app/paysage/page.tsx",
    preuves: ['nom: "Terrasse bois"', "Bientôt", "href: null"],
    lieu: true,
  },
  // --- Plan d'arrosage ------------------------------------------------------
  {
    id: "paysage-arrosage",
    ecran: "Plan d'arrosage",
    ou: "« Paysage » dans la barre du bas, puis Plan d'arrosage automatique",
    intitule: "Faire un plan d'arrosage automatique",
    motsCles: ["arrosage", "plan", "reseau", "arroseur", "turbine", "tuyere", "croquis", "piquage", "nourrice", "automatique"],
    geste:
      "Choisissez l'endroit dans « Le piquage se fait… », puis touchez « Ajouter la photo du croquis » " +
      "et prenez ou choisissez la photo : le plan sort tout seul.",
    reserve:
      "Le croquis doit porter les métrés, l'endroit définitif de la nourrice et l'endroit du piquage. " +
      "Sans les trois, aucun plan n'est proposé.",
    source: ARROSAGE,
    preuves: [
      "Le piquage se fait…",
      "Juste après le compteur d’eau",
      "Robinet de jardin",
      '"Ajouter la photo du croquis"',
      "Votre croquis doit impérativement contenir les métrés",
    ],
  },
  {
    id: "arrosage-mesure-robinet",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique",
    intitule: "Entrer la pression ou le débit quand on se branche sur un robinet de jardin",
    motsCles: ["pression", "debit", "bar", "seau", "robinet", "manometre", "kit", "statique", "dynamique", "mesure"],
    geste:
      "Dans « Le piquage se fait… », choisissez « Robinet de jardin », puis remplissez « Bar statique » " +
      "et « Bar dynamique » relevés au kit buse 5, ou le temps de remplissage d'un seau de 10 L.",
    reserve:
      "Ces cases n'apparaissent qu'au robinet de jardin : juste après le compteur, rien n'est à mesurer. " +
      "Sans seau ni pression dynamique, le plan est refusé, et le seau seul est trop approximatif : prenez le kit.",
    source: ARROSAGE,
    preuves: [
      "Robinet de jardin",
      "Kit débit / pression, buse 5",
      "Bar statique",
      "Bar dynamique",
      "Mesure au seau",
      "Un seau de 10 L rempli en… secondes",
      "Trop approximatif pour calculer un arrosage : prenez le kit.",
      'piquage !== "compteur"',
    ],
    ailleurs: [{ source: "src/lib/arrosage/mesure-debit.ts", preuves: ["Aucune mesure : chronométrez un seau de "] }],
  },
  {
    id: "arrosage-croquis-refuse",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique",
    intitule: "Le croquis est refusé, il manque quelque chose",
    motsCles: ["refuse", "refus", "manque", "croquis", "photo", "reprendre", "incomplet", "nourrice", "metres"],
    geste:
      "L'écran coche ce qu'il a lu parmi « Les métrés », « Le piquage » et « La nourrice », et marque en rouge ce qui manque. " +
      "Complétez le croquis, puis touchez « Reprendre la photo ».",
    source: ARROSAGE,
    preuves: ['quoi="Les métrés"', 'quoi="Le piquage"', 'quoi="La nourrice"', "Reprendre la photo"],
  },
  {
    id: "arrosage-croquis-non-lu",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique",
    intitule: "Le croquis ne sera pas lu, message rouge avant la photo",
    motsCles: ["lu", "lecture", "ia", "marche", "croquis", "cle", "erreur", "rouge"],
    geste:
      "Le message rouge qui finit par « Le croquis ne sera pas lu. » dit pourquoi l'IA ne peut pas lire l'image sur ce serveur. " +
      "Tant qu'il est là, photographier ne donnera aucun plan.",
    source: ARROSAGE,
    preuves: ["Le croquis ne sera pas lu.", "!iaPrete && motifIA"],
  },
  {
    id: "arrosage-reseaux",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique, sous le plan",
    intitule: "Lire les réseaux : quelle zone, quel arroseur, quelle buse",
    motsCles: ["reseau", "reseaux", "vanne", "vannes", "buse", "arroseurs", "portee", "debit", "zone"],
    geste:
      "Sous le dessin, une carte par réseau : la zone arrosée, le matériel et sa buse avec sa portée, " +
      "puis le compte des arroseurs, tés, coudes et mètres de tuyau.",
    source: ARROSAGE,
    preuves: ["Réseau {i + 1}", 'data-atlas="carte-reseau"', ", portée ${virgule(m.portee)} m"],
    lieu: true,
  },
  {
    id: "arrosage-reserves",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique, juste sous le dessin",
    intitule: "Savoir ce que le plan n'a pas pu calculer",
    motsCles: ["reserve", "reserves", "avertissement", "calcule", "suppose", "attention", "point", "rouge"],
    geste: "Lisez les lignes marquées d'un point rouge juste sous le dessin : c'est ce que le calcul n'a pas pu compter ou a dû supposer.",
    source: ARROSAGE,
    preuves: ['data-atlas="reserves"', "backgroundColor: colors.alert"],
    lieu: true,
  },
  {
    id: "arrosage-legende",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique, sous le dessin",
    intitule: "Comprendre les symboles du plan",
    motsCles: ["legende", "symbole", "rond", "carre", "losange", "plein", "creux", "coude", "te", "antenne"],
    geste:
      "La légende est sous le dessin : rond, une turbine ; carré, une tuyère ; plein, un té taraudé ; " +
      "creux, un coude taraudé en fin de ligne ; losange, un té égal ; trait fin, l'antenne Ø16 ; le trait large, la tranchée.",
    source: "src/app/paysage/arrosage/PlanDessine.tsx",
    preuves: [
      "</b> : une turbine",
      "</b> : une tuyère",
      "la ligne continue, té taraudé",
      "la ligne s’arrête là, coude taraudé",
      "la ligne se sépare, té égal 25×25×25",
      "l’antenne Ø16 rigide, 2 m au plus",
      "la tranchée",
    ],
    lieu: true,
  },
  {
    id: "arrosage-diametre-tuyau",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique, sous les réseaux",
    intitule: "Savoir quand passer du tuyau Ø25 au Ø32",
    motsCles: ["diametre", "tuyau", "25", "32", "pehd", "longueur", "metres", "seuil"],
    geste: "Sous les cartes des réseaux, une ligne dit jusqu'à combien de mètres le Ø25 tient, et le Ø32 au-delà.",
    reserve: "Quand le débit est trop fort pour le Ø25, elle dit Ø32 d'office.",
    source: ARROSAGE,
    preuves: ["Ø32 au-delà.", "Ø32 d’office", 'data-atlas="seuil-tuyau"'],
  },
  {
    id: "arrosage-liste-pieces",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique, sous le plan",
    intitule: "Trouver la liste des pièces à commander",
    motsCles: ["pieces", "liste", "commande", "commander", "fournisseur", "materiel", "raccords", "quantites", "nomenclature"],
    geste:
      "Sous les réseaux, à « Le détail des pièces » : ce qui va du compteur à la nourrice, ce qui est dans le regard, puis ce qui part au jardin.",
    reserve: "« à mesurer » : la longueur ne se lit pas sur le croquis, relevez-la sur place.",
    source: ARROSAGE,
    preuves: ["Le détail des pièces", '"à mesurer"', "TITRES_DES_ZONES[zone]"],
    ailleurs: [{ source: "src/lib/arrosage/pieces.ts", preuves: ['"Du compteur à la nourrice"', '"Dans le regard"', '"Au jardin"'] }],
    lieu: true,
  },
  {
    id: "arrosage-modifier-plan",
    ecran: "Plan d'arrosage",
    ou: "« Paysage », Plan d'arrosage automatique, tout en bas sous la liste des pièces",
    intitule: "Demander une modification du plan : marque, matériel, buse",
    motsCles: ["modifier", "changer", "marque", "materiel", "buse", "discuter", "demander", "corriger", "modification"],
    geste:
      "Sous « Demander une modification », écrivez ce que vous voulez changer dans « Écrire à Atlas… », " +
      "par exemple une marque, un matériel ou une buse, puis touchez le bouton rond d'envoi : le plan se refait.",
    reserve:
      "La discussion n'existe qu'avec un plan à l'écran. Pour changer un métré ou l'endroit de la nourrice, " +
      "corrigez le croquis et reprenez la photo.",
    source: "src/app/paysage/arrosage/DiscuterLePlan.tsx",
    preuves: [
      "Demander une modification",
      'placeholder="Écrire à Atlas…"',
      'aria-label="Envoyer la demande"',
      "Pour changer un métré ou l’endroit de la nourrice, corrigez le croquis et",
    ],
    ailleurs: [
      { source: "src/lib/arrosage/consignes.ts", preuves: ['quoi: "marque"'] },
      { source: ARROSAGE, preuves: ["<DiscuterLePlan"] },
    ],
  },
  // --- Diagnostic végétal ---------------------------------------------------
  {
    id: "diagnostic-details",
    ecran: "Diagnostic végétal",
    ou: "« Paysage », Diagnostic végétal, après la photo",
    intitule: "Voir le traitement, la prévention et les sources d'un diagnostic",
    motsCles: ["traitement", "traiter", "prevention", "sources", "details", "gravite", "faire", "produit", "soigner", "maladie", "voir"],
    geste:
      "Sur le résultat, la gravité et « Que faire ? » s'affichent d'emblée. Touchez « Voir les détails » " +
      "pour le nom scientifique, la prévention, le traitement et les sources.",
    source: DIAG,
    preuves: ['cle="Gravité"', 'cle="Que faire ?"', "Voir les détails", 'cle="Traitement"', 'cle="Prévention"'],
  },
  {
    id: "diagnostic-rattacher",
    ecran: "Diagnostic végétal",
    ou: "« Paysage », Diagnostic végétal, résultat, puis Voir les détails",
    intitule: "Rattacher un diagnostic à un chantier",
    motsCles: ["rattacher", "lier", "associer", "chantier", "diagnostic", "joindre", "relier"],
    geste: "Ouvrez « Voir les détails », choisissez le chantier sous « Rattacher à un chantier », puis touchez « Rattacher ».",
    reserve: "Il faut un chantier ouvert. Sans lui, le diagnostic reste indépendant.",
    source: "src/app/paysage/diagnostic/[id]/RattacherAUnChantier.tsx",
    preuves: ["Rattacher à un chantier", '"Rattacher"', "Aucun chantier ouvert"],
    ailleurs: [{ source: DIAG, preuves: ["Voir les détails", "<RattacherAUnChantier"] }],
  },
  {
    id: "diagnostic-nouvelle-photo",
    ecran: "Diagnostic végétal",
    ou: "« Paysage », Diagnostic végétal, résultat",
    intitule: "Faire un autre diagnostic",
    motsCles: ["autre", "nouveau", "nouvelle", "diagnostic", "photo", "recommencer", "encore"],
    geste: "Sur le résultat, touchez « Nouvelle photo ».",
    source: DIAG,
    preuves: ['"Nouvelle photo"'],
  },
  {
    id: "diagnostic-photo-de-plus",
    ecran: "Diagnostic végétal",
    ou: "« Paysage », Diagnostic végétal, après la photo",
    intitule: "Atlas demande une photo de plus",
    motsCles: ["photo", "plus", "deuxieme", "complement", "autre", "consigne", "demande"],
    geste: "Suivez la consigne écrite, puis touchez « Prendre cette photo ». « Recommencer » repart de zéro.",
    reserve: "Une seule photo de plus, jamais deux.",
    source: DIAG,
    preuves: ['libelle="Prendre cette photo"', "Recommencer", "Une seule photo de plus, jamais deux."],
  },
  {
    id: "diagnostic-sans-conclusion",
    ecran: "Diagnostic végétal",
    ou: "« Paysage », Diagnostic végétal, après la photo",
    intitule: "Le diagnostic reste sans conclusion",
    motsCles: ["conclusion", "inconnu", "trouve", "reconnu", "rien", "echec", "confirmer"],
    geste:
      "Lisez « Vu sur la photo » et « Pourquoi ça ne suffit pas », puis touchez « Recommencer » pour une nouvelle photo.",
    source: DIAG,
    preuves: ['"Sans conclusion"', "Vu sur la photo", "Pourquoi ça ne suffit pas", '"Recommencer"'],
  },
  {
    id: "diagnostic-echoue",
    ecran: "Diagnostic végétal",
    ou: "« Paysage », Diagnostic végétal, après la photo",
    intitule: "La photo n'a pas été regardée",
    motsCles: ["regardee", "echoue", "panne", "reessayer", "marche", "analyse", "erreur"],
    geste: "Touchez « Réessayer ». Si cela recommence, ouvrez « Réglages de l’IA ».",
    source: "src/app/paysage/diagnostic/[id]/Reessayer.tsx",
    preuves: ['"Réessayer"', "Réglages de l’IA"],
    ailleurs: [{ source: DIAG, preuves: ["La photo n’a pas été regardée"] }],
  },
  // --- Fiches de sécurité ---------------------------------------------------
  {
    id: "securite-ouvrir-pdf",
    ecran: "Fiches de sécurité",
    ou: "« Paysage » dans la barre du bas, puis Fiches de sécurité",
    intitule: "Ouvrir ou enregistrer le PDF d'une fiche de sécurité signée",
    motsCles: ["pdf", "ouvrir", "voir", "enregistrer", "telecharger", "securite", "signee", "imprimer", "ouvre", "fiche"],
    geste:
      "Touchez la fiche pour l'ouvrir, puis « Ouvrir le PDF ». « Enregistrer le PDF » la met dans les fichiers du téléphone.",
    reserve: "Elle est gardée deux ans après la signature, même si le chantier est supprimé.",
    source: SECU,
    preuves: ["Ouvrir le PDF", "Enregistrer le PDF", "Gardée deux ans après la signature, même si le chantier est supprimé."],
  },
  {
    id: "securite-transmettre",
    ecran: "Fiches de sécurité",
    ou: "« Paysage », Fiches de sécurité",
    intitule: "Transmettre une fiche de sécurité signée",
    motsCles: ["transmettre", "envoyer", "partager", "securite", "pdf", "fiche", "donneur"],
    geste: "Touchez la fiche, puis « Transmettre le PDF » et choisissez à qui l'envoyer.",
    reserve: "Le bouton disparaît une fois la fiche transmise ; la ligne porte alors « transmise ».",
    source: SECU,
    preuves: ["Transmettre le PDF", "!transmise &&", '"transmise"'],
  },
  {
    id: "securite-periode",
    ecran: "Fiches de sécurité",
    ou: "« Paysage », Fiches de sécurité, en haut",
    intitule: "Voir les fiches de sécurité d'un autre mois, d'un jour ou d'une année",
    motsCles: ["mois", "jour", "annee", "date", "periode", "filtre", "filtrer", "ancienne"],
    geste:
      "En haut, touchez le jour, le mois ou l'année pour ne voir que cette période. Le petit chevron à côté ouvre la roue pour choisir une autre date.",
    source: SECU,
    preuves: ["<FiltreDeDate"],
    ailleurs: [{ source: FILTRE, preuves: ['data-atlas="periode-choisie"', 'aria-label="Choisir un jour"'] }],
  },
  {
    id: "securite-chercher",
    ecran: "Fiches de sécurité",
    ou: "« Paysage », Fiches de sécurité",
    intitule: "Chercher une fiche de sécurité par client",
    motsCles: ["chercher", "rechercher", "client", "nom", "trouver", "securite", "fiche"],
    geste: "Tapez le nom dans « Chercher un client ». La croix efface la recherche.",
    source: SECU,
    preuves: ['placeholder="Chercher un client"', 'aria-label="Effacer la recherche"'],
  },
  // --- Fiche de chantier ----------------------------------------------------
  {
    id: "paysage-fiche",
    ecran: "Fiche de chantier",
    ou: "« Paysage » dans la barre du bas, puis Fiche de chantier",
    intitule: "Remplir une fiche de chantier et l'envoyer au client",
    motsCles: ["fiche", "chantier", "entretien", "cocher", "rapport", "compte", "rendu", "envoyer", "passage", "intervention"],
    geste:
      "Touchez « Créer une fiche », puis « + Ajouter un client », cochez les prestations faites, ajoutez vos observations, " +
      "puis « Enregistrer et envoyer » : le SMS ou l'e-mail s'ouvre, prêt à partir.",
    reserve: "Sans client nommé et sans une prestation cochée, l'envoi est refusé. Un rapport parti ne se modifie plus.",
    source: FICHE,
    preuves: ["+ Ajouter un client", "Enregistrer et envoyer", "Observations"],
    ailleurs: [
      { source: "src/app/paysage/fiche/OuvrirFiche.tsx", preuves: ['"Créer une fiche"'] },
      {
        source: "src/lib/passage-entretien.ts",
        preuves: ["Nommez d'abord le client", "Cochez au moins une prestation avant d'envoyer.", "Il ne se renvoie pas."],
      },
    ],
  },
  {
    id: "fiche-chantier-autre-jour",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier",
    intitule: "Faire la fiche d'un autre jour que aujourd'hui",
    motsCles: ["jour", "date", "hier", "autre", "passage", "changer", "fiche"],
    geste: "Au-dessus de « Créer une fiche », touchez le jour écrit : la roue s'ouvre, choisissez le jour du passage.",
    source: "src/app/paysage/fiche/OuvrirFiche.tsx",
    preuves: ['dataAtlas="jour-du-passage"', '"Créer une fiche"'],
    ailleurs: [{ source: FILTRE, preuves: ['aria-label="Choisir un jour"'] }],
  },
  {
    id: "fiche-chantier-client",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, une fiche ouverte",
    intitule: "Choisir ou changer le client d'une fiche de chantier",
    motsCles: ["client", "changer", "choisir", "nommer", "ajouter", "qui", "fiche"],
    geste:
      "Touchez « + Ajouter un client », ou « Changer » à côté de son nom, cherchez-le dans « Chercher un client » et touchez son nom.",
    reserve:
      "Les prestations de son dernier chantier se cochent toutes seules. Un client ne se crée pas ici : il naît d'un devis.",
    source: FICHE,
    preuves: [
      "+ Ajouter un client",
      "Changer",
      "Pour qui ?",
      'placeholder="Chercher un client"',
      "prestations cochées, celles du dernier chantier.",
      "Vos clients se créent au fil des devis.",
    ],
  },
  {
    id: "fiche-chantier-sms-email",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, une fiche ouverte, sous le nom du client",
    intitule: "Envoyer la fiche par SMS ou par e-mail",
    motsCles: ["sms", "email", "mail", "texto", "message", "canal", "envoyer", "choisir"],
    geste: "Sous le nom du client, à « Envoyé par », touchez « SMS » ou « E-mail ».",
    reserve: "« absent » veut dire que ce numéro ou cet e-mail manque dans sa fiche : l'envoi par ce moyen est alors refusé.",
    source: FICHE,
    preuves: ["Envoyé par", 'mot: "SMS"', 'mot: "E-mail"', ", absent"],
  },
  {
    id: "fiche-chantier-temps",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, une fiche ouverte",
    intitule: "Noter le temps passé, et le montrer ou non au client",
    motsCles: ["temps", "heures", "minutes", "duree", "passe", "masquer", "cacher", "visible", "afficher"],
    geste:
      "À « Temps passé », choisissez les heures et les minutes. L'interrupteur à côté le rend « Visible » ou « Masqué » sur le rapport du client.",
    source: FICHE,
    preuves: ["Temps passé", 'aria-label="Heures"', 'aria-label="Minutes"', '"Visible"', '"Masqué"'],
  },
  {
    id: "fiche-chantier-renvoyer",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, un rapport déjà envoyé",
    intitule: "Rouvrir le message d'une fiche déjà envoyée",
    motsCles: ["renvoyer", "relancer", "message", "sms", "email", "lien", "envoye", "copier"],
    geste: "Ouvrez la fiche envoyée, puis touchez « Envoyer par SMS » ou « Envoyer par e-mail » : le message se rouvre.",
    reserve:
      "Les cases ne se modifient plus. Si le client n'a ni téléphone ni e-mail, copiez le lien affiché sous la phrase.",
    source: FICHE,
    preuves: ['"Envoyer par SMS"', '"Envoyer par e-mail"', "Copiez le lien ci-dessous.", "Envoyé le"],
  },
  {
    id: "fiche-chantier-supprimer",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, liste En cours",
    intitule: "Supprimer une fiche de chantier pas encore envoyée",
    motsCles: ["supprimer", "effacer", "enlever", "retirer", "virer", "brouillon", "fiche", "croix"],
    geste: "Sous « En cours », touchez la croix au bout de la ligne. « Annuler » reste quelques secondes en bas pour se raviser.",
    reserve: "Seules les fiches marquées « Brouillon » se suppriment ; un rapport envoyé reste.",
    source: "src/app/paysage/fiche/FichesEnCours.tsx",
    preuves: ["En cours", "Supprimer la fiche ", "×"],
    ailleurs: [
      { source: TIROIR, preuves: ["Annuler"] },
      { source: "src/app/paysage/fiche/LignePassage.tsx", preuves: ["Brouillon"] },
    ],
  },
  {
    id: "fiche-chantier-reprendre",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, liste En cours",
    intitule: "Reprendre une fiche commencée et pas envoyée",
    motsCles: ["reprendre", "continuer", "brouillon", "commencee", "cours", "finir", "rouvrir"],
    geste: "Sous « En cours », touchez la ligne marquée « Brouillon ».",
    source: "src/app/paysage/fiche/FichesEnCours.tsx",
    preuves: ["En cours", "href={`/paysage/fiche/${p.id}`}"],
    ailleurs: [{ source: "src/app/paysage/fiche/LignePassage.tsx", preuves: ["Brouillon"] }],
    lieu: true,
  },
  {
    id: "fiche-chantier-rapports-envoyes",
    ecran: "Fiche de chantier",
    ou: "« Paysage », Fiche de chantier, en bas",
    intitule: "Retrouver les rapports de fiche déjà envoyés",
    motsCles: ["rapports", "envoyes", "anciens", "retrouver", "historique", "mois", "chercher", "sont"],
    geste:
      "Descendez à « Rapports envoyés » : touchez le jour, le mois ou l'année pour choisir la période, ou tapez un nom de client, puis touchez la ligne.",
    source: "src/app/paysage/fiche/RapportsEnvoyes.tsx",
    preuves: ["Rapports envoyés", 'placeholder="Un nom de client"', "<FiltreDeDate"],
    ailleurs: [{ source: FILTRE, preuves: ['data-atlas="periode-choisie"'] }],
    lieu: true,
  },
  // --- Composer ma fiche ----------------------------------------------------
  {
    id: "composer-ajouter-prestation",
    ecran: "Composer ma fiche",
    ou: "« Paysage », Fiche de chantier, puis Composer ma fiche",
    intitule: "Ajouter une prestation à cocher sur la fiche",
    motsCles: ["ajouter", "prestation", "ligne", "nouvelle", "fiche", "cocher", "tache"],
    geste:
      "Sous la famille voulue, touchez « + Ajouter une prestation », écrivez son nom, puis « Ajouter à » suivi du nom de la famille.",
    source: COMPOSER,
    preuves: ["+ Ajouter une prestation", 'placeholder="Nom de la prestation"', "Ajouter à {f.famille}"],
  },
  {
    id: "composer-ajouter-famille",
    ecran: "Composer ma fiche",
    ou: "« Paysage », Fiche de chantier, puis Composer ma fiche",
    intitule: "Ajouter une famille de prestations",
    motsCles: ["famille", "categorie", "rubrique", "groupe", "ajouter", "nouvelle", "creer"],
    geste: "En bas, touchez « + Ajouter une famille », écrivez son nom et sa première prestation, puis « Créer la famille ».",
    source: COMPOSER,
    preuves: ["+ Ajouter une famille", 'placeholder="Nom de la famille"', 'placeholder="Sa première prestation"', "Créer la famille"],
  },
  {
    id: "composer-renommer",
    ecran: "Composer ma fiche",
    ou: "« Paysage », Fiche de chantier, puis Composer ma fiche",
    intitule: "Renommer une prestation ou une famille",
    motsCles: ["renommer", "nom", "modifier", "corriger", "changer", "prestation", "famille", "libelle"],
    geste: "Touchez le nom de la prestation ou de la famille et corrigez-le : c'est enregistré dès que vous quittez la case.",
    reserve: "Cela ne change aucun rapport déjà envoyé.",
    source: COMPOSER,
    preuves: ["Prestation ${p.libelle}", "Nom de la famille ${f.famille}", "onBlur", "aucun rapport déjà envoyé"],
  },
  {
    id: "composer-retirer-prestation",
    ecran: "Composer ma fiche",
    ou: "« Paysage », Fiche de chantier, puis Composer ma fiche",
    intitule: "Retirer une prestation de la fiche",
    motsCles: ["retirer", "supprimer", "enlever", "effacer", "virer", "prestation", "ligne", "croix"],
    geste: "Touchez la croix au bout de la prestation. « Annuler » reste quelques secondes en bas pour se raviser.",
    source: COMPOSER,
    preuves: ["Retirer ${p.libelle}", "×"],
    ailleurs: [{ source: TIROIR, preuves: ["Annuler"] }],
  },
  {
    id: "composer-retirer-famille",
    ecran: "Composer ma fiche",
    ou: "« Paysage », Fiche de chantier, puis Composer ma fiche",
    intitule: "Retirer une famille entière et ses prestations",
    motsCles: ["retirer", "supprimer", "enlever", "effacer", "famille", "categorie", "rubrique", "toute"],
    geste: "À côté du nom de la famille, touchez « Retirer la famille ». « Annuler » reste quelques secondes en bas pour se raviser.",
    reserve: "Toutes ses prestations partent avec elle.",
    source: COMPOSER,
    preuves: ["Retirer la famille", "et ses ${f.lignes.length} prestation"],
    ailleurs: [{ source: TIROIR, preuves: ["Annuler"] }],
  },
  // --- Clients --------------------------------------------------------------
  {
    id: "clients-chercher",
    ecran: "Vos clients",
    ou: "« Chantiers » dans la barre du bas, puis « Vos clients »",
    intitule: "Chercher un client par son nom",
    motsCles: ["chercher", "rechercher", "client", "nom", "trouver", "retrouver", "filtrer"],
    geste: "En haut de « Vos clients », tapez une partie de son nom dans « Chercher un client ».",
    reserve: "La recherche porte sur le nom du client.",
    source: "src/app/clients/ListeClients.tsx",
    preuves: ['placeholder="Chercher un client"', "filtrerClientsParNom(clients, saisie)"],
    ailleurs: [{ source: "src/app/EcranChantiers.tsx", preuves: ['href="/clients"', "Vos clients"] }],
  },
  {
    id: "clients-creer",
    ecran: "Vos clients",
    ou: "« Chantiers » dans la barre du bas, puis « Vos clients »",
    intitule: "Créer un nouveau client",
    motsCles: ["creer", "nouveau", "ajouter", "client", "enregistrer", "fiche", "carnet"],
    geste: "Un client ne se crée pas à part : il naît avec son chantier, puis apparaît dans « Vos clients ».",
    source: "src/app/clients/page.tsx",
    preuves: ["Ils naissent avec vos chantiers."],
  },
  {
    id: "clients-modifier",
    ecran: "Ses coordonnées",
    ou: "« Chantiers », « Vos clients », puis son nom",
    intitule: "Modifier le nom, le téléphone, l'e-mail ou l'adresse d'un client",
    motsCles: ["modifier", "changer", "corriger", "coordonnees", "telephone", "numero", "adresse", "email", "nom", "civilite"],
    geste: "Sur sa fiche, touchez « Modifier ses coordonnées », corrigez les cases, puis « Enregistrer ».",
    reserve: "Le nom ne peut pas être vide.",
    source: "src/app/clients/[id]/coordonnees/SesCoordonnees.tsx",
    preuves: ['libelle="Nom du client"', 'libelle="Téléphone"', 'libelle="E-mail"', 'label="Son adresse"', '"Enregistrer"'],
    ailleurs: [
      { source: DOSSIER, preuves: ["Modifier ses coordonnées"] },
      { source: "src/app/clients/[id]/coordonnees/actions.ts", preuves: ["Le nom ne peut pas être vide."] },
    ],
  },
  {
    id: "clients-dernier-devis",
    ecran: "Client",
    ou: "« Chantiers », « Vos clients », puis son nom",
    intitule: "Refaire pour un client le même devis que la dernière fois",
    motsCles: ["refaire", "meme", "dernier", "devis", "copier", "dupliquer", "reprendre", "recommencer"],
    geste: "Sur sa fiche, touchez « Dernier devis » : un devis neuf s'ouvre, repris de ce qu'on lui a fait la dernière fois.",
    reserve: "Le bouton n'apparaît que si un devis a déjà été fait pour ce client. L'ancien devis ne change pas.",
    source: "src/app/clients/[id]/RepartirDeCeClient.tsx",
    preuves: ['"Dernier devis"', "dernierChantierId && (", "/devis-complet"],
    ailleurs: [{ source: DOSSIER, preuves: ["<RepartirDeCeClient"] }],
  },
  {
    id: "clients-autre-chantier",
    ecran: "Client",
    ou: "« Chantiers », « Vos clients », puis son nom",
    intitule: "Ouvrir un nouveau chantier pour un client déjà connu",
    motsCles: ["nouveau", "autre", "chantier", "client", "connu", "ancien", "retaper", "ouvrir"],
    geste: "Sur sa fiche, touchez « Autre chantier » : le chantier s'ouvre avec ses coordonnées déjà remplies.",
    source: "src/app/clients/[id]/RepartirDeCeClient.tsx",
    preuves: ["Autre chantier", "/chantiers/nouveau?client="],
    ailleurs: [{ source: DOSSIER, preuves: ["<RepartirDeCeClient"] }],
  },
  {
    id: "clients-derniere-prestation",
    ecran: "Client",
    ou: "« Chantiers », « Vos clients », puis son nom",
    intitule: "Voir ce qu'on a fait la dernière fois chez un client",
    motsCles: ["derniere", "fois", "prestation", "fait", "historique", "precedent", "quand"],
    geste: "Touchez son nom dans « Vos clients » : « Dernière prestation » est sous ses coordonnées.",
    source: DOSSIER,
    preuves: ["Dernière prestation", "fiche.derniere.comprend"],
    lieu: true,
  },
  {
    id: "clients-document",
    ecran: "Client",
    ou: "« Chantiers », « Vos clients », puis son nom",
    intitule: "Ouvrir, enregistrer ou partager un devis, une facture ou une fiche d'un client",
    motsCles: ["ouvrir", "partager", "enregistrer", "telecharger", "whatsapp", "document", "pdf", "copie"],
    geste:
      "Sur sa fiche, choisissez l'onglet « Devis », « Factures » ou « Fiches », touchez le document, puis « Ouvrir », « Enregistrer » ou « Partager ».",
    reserve: "« Enregistrer » n'apparaît pas quand le document est une page plutôt qu'un PDF.",
    source: "src/app/clients/[id]/PieceDuDossier.tsx",
    preuves: ["que faire de ce document ?", "Ouvrir", "Partager", "Enregistrer", "estUnFichier && ("],
    ailleurs: [{ source: DOSSIER, preuves: ['libelle: "Devis"', 'libelle: "Factures"', 'libelle: "Fiches"'] }],
  },
  {
    id: "clients-supprimer",
    ecran: "Client",
    ou: "« Chantiers », « Vos clients », puis son nom, tout en bas",
    intitule: "Supprimer un client",
    motsCles: ["supprimer", "effacer", "enlever", "virer", "retirer", "client", "definitivement", "rgpd"],
    geste:
      "Tout en bas de sa fiche, touchez « Supprimer ce client ». S'il a des documents, cochez « J’ai sauvegardé ces documents ailleurs », puis « Supprimer ».",
    reserve:
      "C'est définitif : ses devis, photos et notes sont détruits. Les factures que la loi oblige à garder restent, sous « Conservé par la loi ».",
    source: "src/app/clients/[id]/SupprimerCeClient.tsx",
    preuves: ["Supprimer ce client", "J’ai sauvegardé ces documents ailleurs", '"Supprimer"', "Conservé par la loi", "C’est définitif."],
  },
  // --- Catalogue ------------------------------------------------------------
  {
    id: "catalogue-mots",
    ecran: "Catalogue",
    ou: "« Réglages » dans la barre du bas, puis Tarifs & catalogue, puis Le catalogue",
    intitule: "Apprendre à Atlas un mot du métier",
    motsCles: ["mot", "mots", "vocabulaire", "catalogue", "comprendre", "apprendre", "dictee", "ecime", "jargon", "synonyme"],
    geste: "Sous la prestation ou le matériel, touchez « + mon mot », écrivez le mot tel que vous le dites, puis « Ajouter ».",
    reserve: "Vos mots s'ajoutent à la ligne « Aussi appelé ».",
    source: MOTS,
    preuves: ["+ mon mot", "Comme vous le dites", "Ajouter", "Aussi appelé"],
  },
  {
    id: "catalogue-ouvrir",
    ecran: "Catalogue",
    ou: "« Réglages » dans la barre du bas, puis Tarifs & catalogue",
    intitule: "Trouver le catalogue des prestations et matériels",
    motsCles: ["catalogue", "prestations", "materiels", "liste", "trouver", "sont", "vocabulaire"],
    geste: "Touchez « Réglages » dans la barre du bas, puis « Tarifs & catalogue », puis « Le catalogue ».",
    reserve: "Le catalogue ne porte aucun prix : les prix sont dans « Mes prix », juste au-dessus.",
    source: "src/app/reglages/tarifs/page.tsx",
    preuves: ['href="/catalogue"', 'nom="Le catalogue"', "Il ne porte aucun prix.", 'nom="Mes prix"'],
    ailleurs: [{ source: "src/lib/rubriques-reglages.ts", preuves: ['nom: "Tarifs & catalogue"'] }],
    lieu: true,
  },
  {
    id: "catalogue-nouvelle-entree",
    ecran: "Catalogue",
    ou: "« Réglages », Tarifs & catalogue, puis Le catalogue",
    intitule: "Ajouter une prestation ou un matériel au catalogue",
    motsCles: ["ajouter", "nouvelle", "nouveau", "prestation", "materiel", "catalogue", "creer"],
    geste: "Sous « Prestations » ou « Matériels », touchez « + Nouvelle prestation » ou « + Nouveau matériel », écrivez son nom, puis « Créer ».",
    source: "src/app/catalogue/page.tsx",
    preuves: ['titre="Prestations"', 'titre="Matériels"', '"+ Nouvelle prestation"', '"+ Nouveau matériel"'],
    ailleurs: [{ source: MOTS, preuves: ['placeholder="Son nom"', "Créer"] }],
  },
  {
    id: "catalogue-retirer-mot",
    ecran: "Catalogue",
    ou: "« Réglages », Tarifs & catalogue, puis Le catalogue",
    intitule: "Retirer un mot qu'on avait appris à Atlas",
    motsCles: ["retirer", "supprimer", "enlever", "effacer", "mot", "vocabulaire", "croix"],
    geste: "Dans la ligne « Aussi appelé », touchez la croix à côté de votre mot.",
    reserve: "Seuls vos mots portent une croix, pas ceux du catalogue commun.",
    source: MOTS,
    preuves: ["Aussi appelé", "Retirer le mot « ${m.mot} »", "carte.mesMots.map"],
  },
  {
    id: "catalogue-mots-proposes",
    ecran: "Catalogue",
    ou: "« Réglages », Tarifs & catalogue, puis Le catalogue, en haut",
    intitule: "Accepter ou refuser un mot qu'Atlas a entendu dans une dictée",
    motsCles: ["propose", "entendu", "retenir", "accepter", "refuser", "mot", "dictee", "suggestion"],
    geste: "Sous « Atlas a entendu ces mots », touchez « Oui, retenir » ou « Non ».",
    reserve: "Ce bloc n'apparaît que quand Atlas a relevé un mot inconnu dans vos dictées.",
    source: "src/app/catalogue/MotsProposes.tsx",
    preuves: ["Atlas a entendu ces mots", "Oui, retenir", "Non", "restants.length === 0"],
  },
  // --- Clients --------------------------------------------------------------
  {
    id: "clients-liste",
    ecran: "Vos clients",
    ou: "« Chantiers » dans la barre du bas, puis « Vos clients »",
    intitule: "Retrouver un client et tout ce qui le concerne",
    motsCles: ["client", "clients", "fiche", "retrouver", "historique", "dossier", "devis", "facture", "liste", "carnet", "voir", "tous"],
    // **« Fiche chantier » est devenu l'onglet « Fiches »** : la preuve ne
    // tenait plus que par le commentaire qui racontait le changement.
    geste:
      "Touchez « Chantiers » dans la barre du bas, puis « Vos clients », puis son nom : " +
      "ses devis, factures et fiches y sont, un onglet chacun.",
    source: "src/app/clients/[id]/page.tsx",
    preuves: ['libelle: "Devis"', 'libelle: "Factures"', 'libelle: "Fiches"'],
    ailleurs: [{ source: "src/app/EcranChantiers.tsx", preuves: ['href="/clients"', "Vos clients"] }],
    lieu: true,
  },
  {
    id: "paysage-composer-ma-fiche",
    ecran: "Composer ma fiche",
    // **Elle a quitté les Réglages le 26 août 2026**, à sa demande. Le mode
    // d'emploi le dit à l'endroit où il cherchera : « Paysage », pas « Réglages ».
    ou: "« Paysage » dans la barre du bas, Fiche de chantier, puis la carte « Composer ma fiche » sous le titre",
    intitule: "Composer la fiche qu'on coche sur un chantier d'entretien",
    motsCles: ["fiche", "entretien", "modele", "composer", "famille", "prestation", "cocher", "tonte", "rubrique"],
    geste: "Ouvrez « Composer ma fiche », partez du modèle Atlas ou composez la vôtre.",
    reserve: "Réservé au patron. La modifier ne change aucun rapport déjà envoyé.",
    source: "src/app/paysage/fiche/composer/ComposerMaFiche.tsx",
    preuves: ["Partir du modèle Atlas", "Je préfère composer la mienne"],
    ailleurs: [{ source: "src/app/paysage/fiche/page.tsx", preuves: ["Composer ma fiche"] }],
  },
  {
    id: "paysage-diagnostic",
    ecran: "Diagnostic végétal",
    ou: "Paysage, puis Diagnostic végétal",
    intitule: "Savoir ce qu'a un arbre ou une plante",
    motsCles: ["diagnostic", "vegetal", "maladie", "arbre", "feuille", "champignon", "photo", "anomalie", "ecorce"],
    geste: "Appuyez sur « Prendre une photo » et photographiez la zone anormale.",
    source: "src/app/paysage/diagnostic/page.tsx",
    preuves: ["Prendre une photo", "Photographiez la zone qui vous semble anormale."],
  },
];
