/**
 * Mode d'emploi : Les réglages, l'arrivée dans l'application, et l'assistant lui-même.
 *
 * Chaque fiche se prouve contre le code (`scripts/test-mode-emploi.ts`) : la
 * règle, la recherche et le pourquoi vivent dans `src/lib/mode-emploi.ts`.
 */
import type { FicheModeEmploi } from "../mode-emploi";

const R = "« Réglages » dans la barre du bas";

export const FICHES_REGLAGES: FicheModeEmploi[] = [
  // --- Arrivée dans l'application -------------------------------------------
  {
    id: "arrivee-creer-compte",
    ecran: "Créer un compte",
    ou: "l'écran d'accueil d'Atlas, avant d'être connecté",
    intitule: "Créer son compte Atlas, s'inscrire",
    motsCles: ["creer", "compte", "inscrire", "inscription", "nouveau", "commencer", "ouvrir", "premier"],
    geste:
      "Sur l'écran d'accueil, touchez « Créer un compte », répondez à chaque question puis « Continuer ». " +
      "« Passer » saute une question facultative. À la fin, touchez « Entrer dans Atlas ».",
    reserve: "Si Atlas vous envoie un code par e-mail, il faut le saisir avant d'entrer.",
    source: "src/app/bienvenue/page.tsx",
    preuves: ['href="/creer-un-compte"', "Créer un compte"],
    ailleurs: [
      { source: "src/app/creer-un-compte/page.tsx", preuves: ['"Continuer"', "Passer", "Créer mon compte", "Entrer dans Atlas"] },
    ],
  },
  {
    id: "arrivee-code-email",
    ecran: "Créer un compte",
    ou: "juste après la création du compte",
    intitule: "Saisir le code reçu par e-mail, recevoir un nouveau code",
    motsCles: ["code", "email", "mail", "recu", "verification", "verifier", "renvoyer", "chiffres"],
    geste: "Tapez le code reçu par e-mail, puis « Continuer ». Pas reçu ? Touchez « Renvoyer le code ».",
    source: "src/components/atlas/SaisieDuCode.tsx",
    preuves: ["Le code reçu par e-mail", "Renvoyer le code", '"Continuer"'],
  },
  {
    id: "arrivee-se-connecter",
    ecran: "Connexion",
    ou: "l'écran d'accueil d'Atlas, avant d'être connecté",
    intitule: "Se connecter, entrer dans Atlas avec son adresse et son mot de passe",
    motsCles: ["connecter", "connexion", "entrer", "identifier", "login", "adresse", "passe"],
    geste: "Touchez « Se connecter », écrivez votre adresse et votre mot de passe, puis « Entrer ».",
    source: "src/app/login/FormulaireConnexion.tsx",
    preuves: ['placeholder="Adresse"', 'placeholder="Mot de passe"', '"Entrer"'],
    ailleurs: [{ source: "src/app/bienvenue/page.tsx", preuves: ['href="/login"', "Se connecter"] }],
  },
  {
    id: "arrivee-google-apple",
    ecran: "Connexion",
    ou: "l'écran Connexion, en haut",
    intitule: "Se connecter avec Google ou avec Apple",
    motsCles: ["google", "apple", "connecter", "connexion", "compte", "entrer", "gmail", "icloud"],
    geste: "Sur l'écran Connexion, touchez « Google » ou « Apple ».",
    reserve: "Ces deux boutons n'apparaissent que si votre installation d'Atlas les propose.",
    source: "src/app/login/BoutonsFournisseurs.tsx",
    preuves: ["entrerAvecAction", "{f.libelle}"],
    ailleurs: [{ source: "src/lib/fournisseurs-connexion.ts", preuves: ['google: "Google"', 'apple: "Apple"'] }],
  },
  {
    id: "arrivee-face-id",
    ecran: "Connexion",
    ou: "l'écran Connexion",
    intitule: "Entrer dans Atlas avec Face ID, sans taper le mot de passe",
    motsCles: ["face", "faceid", "empreinte", "entrer", "connecter", "connexion", "sans", "rapide"],
    geste: "Sur l'écran Connexion, touchez « Ouvrir avec Face ID ».",
    reserve:
      "Il faut d'abord avoir enregistré ce téléphone dans « Réglages », puis Mot de passe. " +
      "Le bouton n'apparaît que sur un appareil qui sait le faire.",
    source: "src/app/login/LigneFaceId.tsx",
    preuves: ["Ouvrir avec Face ID"],
  },
  {
    id: "arrivee-documents-legaux",
    ecran: "Avant de commencer",
    ou: "à la première entrée, ou quand un document change",
    intitule: "Accepter les conditions d'utilisation pour entrer",
    motsCles: ["conditions", "accepter", "cgu", "confidentialite", "documents", "legaux", "cocher", "lire"],
    geste:
      "Touchez « Lire le texte » pour le lire, cochez « J'ai lu et j'accepte » sous chaque document, puis « Continuer ».",
    reserve: "Atlas ne s'ouvre pas tant que chaque document n'est pas coché.",
    source: "src/app/documents-legaux/formulaire.tsx",
    preuves: ["Lire le texte", "J&apos;ai lu et j&apos;accepte", '"Continuer"'],
    ailleurs: [{ source: "src/app/documents-legaux/page.tsx", preuves: ["Avant de commencer"] }],
  },
  // --- Réglages : l'écran lui-même --------------------------------------------
  {
    id: "reglages-se-deconnecter",
    ecran: "Réglages",
    ou: `${R}, tout en bas de la liste`,
    intitule: "Se déconnecter de ce téléphone",
    motsCles: ["deconnecter", "deconnexion", "sortir", "quitter", "fermer", "session", "partir"],
    geste: "Touchez « Se déconnecter » en bas des réglages, puis encore « Se déconnecter » pour confirmer.",
    source: "src/app/reglages/SeDeconnecter.tsx",
    preuves: ["Se déconnecter", "Annuler"],
    ailleurs: [{ source: "src/app/reglages/page.tsx", preuves: ["<SeDeconnecter"] }],
  },
  {
    id: "reglages-version",
    ecran: "Réglages",
    ou: `${R}, tout en bas`,
    intitule: "Voir quelle version d'Atlas tourne",
    motsCles: ["version", "numero", "mise", "jour", "correctif", "corrections", "derniere"],
    geste: "Descendez tout en bas de « Réglages » : la ligne « Version » donne la date et le numéro servis.",
    source: "src/app/reglages/page.tsx",
    preuves: ["Version", "versionEtRetard"],
    lieu: true,
  },
  {
    id: "reglages-chercher-corrections",
    ecran: "Réglages",
    ou: `${R}, tout en bas, sous Version`,
    intitule: "Récupérer les dernières corrections d'Atlas",
    motsCles: ["corrections", "mise", "jour", "mettre", "chercher", "nouvelle", "version", "recuperer"],
    geste: "Touchez « Chercher les dernières corrections » sous la ligne Version.",
    reserve: "Ce bouton n'existe que sur un espace d'essai, et seulement pour le patron. Rien n'est effacé.",
    source: "src/app/reglages/BoutonMiseAJour.tsx",
    preuves: ["Chercher les dernières corrections"],
    ailleurs: [{ source: "src/app/reglages/page.tsx", preuves: ['role === "proprietaire" && ('] }],
  },
  {
    id: "reglages-reserve-patron",
    ecran: "Réglages",
    ou: R,
    intitule: "Pourquoi un salarié ne voit pas les tarifs ou l'entreprise dans les réglages",
    motsCles: ["salarie", "voir", "vois", "voit", "tarifs", "droits", "reserve", "patron", "manque"],
    geste:
      "Ces rubriques appartiennent au patron. Il peut changer votre rôle dans « Réglages », puis Équipe.",
    source: "src/app/reglages/RubriqueReservee.tsx",
    preuves: ["Ces réglages appartiennent au patron de l&apos;entreprise."],
    ailleurs: [{ source: "src/app/reglages/page.tsx", preuves: ["Rien de l&apos;entreprise ici"] }],
  },
  // --- Tarifs & catalogue -----------------------------------------------------
  {
    id: "reglages-tarifs",
    ecran: "Tarifs & catalogue",
    ou: `${R}, puis Tarifs & catalogue`,
    intitule: "Ajouter, corriger ou retirer un tarif",
    motsCles: ["tarif", "tarifs", "prix", "ajouter", "modifier", "supprimer", "retirer", "unite", "catalogue"],
    geste:
      "Touchez « + Ajouter un tarif », écrivez l'intitulé et le prix, puis touchez la case de l'unité. " +
      "Pour retirer un tarif : glissez sa ligne de droite à gauche, puis « Retirer ».",
    reserve: "Chaque case s'enregistre dès que vous la quittez. Après un retrait, « Annuler » reste un instant en bas.",
    source: "src/app/reglages/ReglagesClient.tsx",
    preuves: ["+ Ajouter un tarif", "Intitulé du tarif", "Prix du tarif", "LigneRetirable", "TiroirDesRetires"],
    ailleurs: [
      { source: "src/components/atlas/LigneRetirable.tsx", preuves: ["Retirer"] },
      { source: "src/components/atlas/ChoixUnite.tsx", preuves: ['aria-label="Unité du tarif"'] },
    ],
  },
  {
    id: "reglages-tarifs-importer",
    ecran: "Tarifs & catalogue",
    ou: `${R}, puis Tarifs & catalogue`,
    intitule: "Importer ses prix depuis un fichier Excel ou CSV",
    motsCles: ["importer", "import", "excel", "csv", "fichier", "tableur", "liste", "tarifs", "charger"],
    geste:
      "Sous « J'ai déjà mes prix ailleurs », touchez « Choisir un fichier ». " +
      "Vérifiez ce qu'Atlas ajouterait, puis « Enregistrer ces tarifs ».",
    reserve: "Rien n'est enregistré avant « Enregistrer ces tarifs ». « Annuler » laisse vos tarifs tels quels.",
    source: "src/app/reglages/ImportTarifs.tsx",
    preuves: ["J&apos;ai déjà mes prix ailleurs", "Choisir un fichier", "Enregistrer ces tarifs", "Annuler"],
  },
  // --- Mes prix et mes mesures ------------------------------------------------
  {
    id: "reglages-prix-case",
    ecran: "Mes prix",
    ou: `${R}, puis Tarifs & catalogue, puis Mes prix`,
    intitule: "Remplir ou effacer un prix dans la grille (abattage, dessouchage, haie)",
    motsCles: ["grille", "case", "diametre", "hauteur", "abattage", "dessouchage", "remplir", "montant", "effacer"],
    geste:
      "Touchez la case du diamètre voulu et écrivez le montant : il s'enregistre en quittant la case. " +
      "Pour l'abattage, touchez d'abord la façon de faire pour ouvrir ses cases. Videz la case pour effacer le prix.",
    reserve: "Une case vide reste une question : Atlas vous la posera sur le chantier.",
    source: "src/app/reglages/prix/GrillesPrixClient.tsx",
    preuves: ["Aucune case remplie sur", "aria-expanded={ouvert}", "onBlur={(e) => onPoser(nature, cle, e.target.value)}"],
  },
  {
    id: "reglages-prix-retirer-travail",
    ecran: "Mes prix",
    ou: `${R}, puis Tarifs & catalogue, puis Mes prix`,
    intitule: "Retirer un travail ou une tranche de la grille des prix",
    motsCles: ["retirer", "supprimer", "enlever", "travail", "tranche", "grille", "croix", "prix"],
    geste: "Touchez la croix à droite du travail ou de la tranche. « Annuler » la remet aussitôt.",
    reserve: "Les prix posés ne sont pas effacés : ils reviennent si vous remettez le travail.",
    source: "src/app/reglages/prix/GrillesPrixClient.tsx",
    preuves: ["Retirer le travail", "Retirer la tranche", "Annuler"],
  },
  {
    id: "reglages-facon-abattre",
    ecran: "Mes prix",
    ou: `${R}, puis Tarifs & catalogue, puis Mes prix, sous l'abattage`,
    intitule: "Ajouter une façon d'abattre (abattage par câble, démontage)",
    motsCles: ["facon", "abattre", "abattage", "technique", "cable", "demontage", "ajouter", "methode"],
    geste: "Sous l'abattage, touchez « + Ajouter une façon d'abattre », écrivez son nom, puis « Ajouter ».",
    source: "src/app/reglages/prix/GrillesPrixClient.tsx",
    preuves: ["Ajouter une façon d&apos;abattre", "Nom de la façon d'abattre", "Ajouter"],
  },
  {
    id: "reglages-mesures",
    ecran: "Mes mesures",
    ou: `${R}, puis Tarifs & catalogue, puis Mes prix, puis « Régler mes mesures »`,
    intitule: "Régler les tranches de diamètre et de hauteur des grilles de prix",
    motsCles: ["mesures", "tranche", "tranches", "diametre", "hauteur", "cm", "borne", "ajouter", "retirer"],
    geste:
      "Touchez « Régler mes mesures », puis « Ajouter un diamètre » ou « Ajouter une hauteur ». " +
      "Écrivez de et à, puis « Ajouter ». Pour retirer une tranche, touchez sa croix.",
    reserve: "Laissez « à » vide pour dire « et plus ». Retirer une tranche n'efface aucun prix, et « Annuler » la remet.",
    source: "src/app/reglages/prix/mesures/MesMesuresClient.tsx",
    preuves: ["Ajouter un diamètre", "Ajouter une hauteur", "Ajouter", "Annuler"],
    ailleurs: [
      { source: "src/app/reglages/prix/GrillesPrixClient.tsx", preuves: ["Régler mes mesures"] },
      { source: "src/app/reglages/prix/mesures/page.tsx", preuves: ["n&apos;efface aucun prix"] },
    ],
  },
  // --- Mon entreprise -------------------------------------------------------
  {
    id: "reglages-forme-juridique",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise`,
    intitule: "Choisir la forme juridique, le capital et la ville du RCS",
    motsCles: ["forme", "juridique", "sasu", "eurl", "sarl", "capital", "rcs", "societe", "statut"],
    geste:
      "Touchez « Forme juridique » et choisissez dans la liste, ou « À écrire vous-même ». " +
      "Pour une société, remplissez ensuite « Capital social » et « Ville du RCS ».",
    source: "src/app/reglages/identite/ChampFormeJuridique.tsx",
    preuves: ["Forme juridique", "À écrire vous-même"],
    ailleurs: [{ source: "src/app/reglages/identite/IdentiteClient.tsx", preuves: ["Capital social", "Ville du RCS"] }],
  },
  {
    id: "reglages-mentions-legales",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, bloc Mentions légales`,
    intitule: "Choisir où s'impriment la forme juridique, le capital et le RCS",
    motsCles: ["mentions", "legales", "imprimer", "capital", "rcs", "forme", "position", "nom", "bas"],
    geste: "Dans « Mentions légales », touchez « Sous le nom », « En bas, avec le SIRET » ou « Ne pas les imprimer ».",
    source: "src/app/reglages/identite/IdentiteClient.tsx",
    preuves: ["Mentions légales", "Sous le nom", "En bas, avec le SIRET", "Ne pas les imprimer"],
  },
  {
    id: "reglages-regime-tva",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, bloc Votre régime de TVA`,
    intitule: "Dire si je facture la TVA ou si je suis en franchise, mon numéro de TVA",
    motsCles: ["tva", "franchise", "assujetti", "assujettie", "regime", "293", "intracommunautaire", "numero"],
    geste:
      "Dans « Votre régime de TVA », touchez « Franchise en base » ou « Assujettie ». " +
      "Assujettie : écrivez votre numéro de TVA intracommunautaire dessous.",
    source: "src/app/reglages/identite/IdentiteClient.tsx",
    preuves: ["Votre régime de TVA", "Franchise en base", "Assujettie", "Numéro de TVA intracommunautaire"],
  },
  {
    id: "reglages-tva-rythme",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, sous Votre régime de TVA`,
    intitule: "Déclarer sa TVA tous les mois ou tous les trimestres",
    motsCles: ["tva", "declarer", "mensuelle", "trimestrielle", "trimestre", "mois", "rythme", "periode"],
    geste: "Sous votre régime de TVA, touchez « Tous les mois » ou « Tous les trimestres ».",
    source: "src/app/reglages/PeriodiciteTva.tsx",
    preuves: ["Tous les mois", "Tous les trimestres"],
    ailleurs: [{ source: "src/app/reglages/identite/page.tsx", preuves: ["<PeriodiciteTvaReglage"] }],
  },
  {
    id: "reglages-tva-exigibilite",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, sous Votre régime de TVA`,
    intitule: "Choisir quand je reverse la TVA : au paiement du client ou à l'envoi de la facture",
    motsCles: ["tva", "debits", "exigible", "exigibilite", "reverser", "reverse", "impots", "moment"],
    geste:
      "Sous « Je reverse ma TVA aux impôts », touchez « Le mois où mon client me paie » " +
      "ou « Le mois où j'envoie la facture ».",
    reserve: "Ce choix doit correspondre à ce que les impôts savent de vous : votre comptable vous le dit.",
    source: "src/app/reglages/ExigibiliteTva.tsx",
    preuves: ["Je reverse ma TVA aux impôts", "Le mois où mon client me paie", "Le mois où j'envoie la facture"],
    ailleurs: [{ source: "src/app/reglages/identite/page.tsx", preuves: ["<ExigibiliteTva"] }],
  },
  {
    id: "reglages-telephone",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise`,
    intitule: "Changer le téléphone et l'e-mail de l'entreprise, l'indicatif du pays",
    motsCles: ["telephone", "numero", "portable", "indicatif", "pays", "belgique", "suisse", "email", "mail"],
    geste:
      "Écrivez le numéro sous « Téléphone ». Pour un autre pays, touchez le drapeau à gauche et choisissez l'indicatif. " +
      "L'e-mail se corrige juste dessous.",
    source: "src/app/reglages/identite/ChampTelephone.tsx",
    preuves: ["Téléphone", "Numéro de téléphone", "Indicatif :"],
    ailleurs: [{ source: "src/app/reglages/identite/IdentiteClient.tsx", preuves: ['etiquette="Adresse e-mail"'] }],
  },
  {
    id: "reglages-iban",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, bloc Pour être payé`,
    intitule: "Changer l'IBAN et le titulaire du compte bancaire",
    motsCles: ["iban", "rib", "banque", "bancaire", "compte", "titulaire", "virement", "coordonnees", "payer"],
    geste:
      "Dans « Pour être payé », corrigez l'IBAN ou le titulaire du compte. " +
      "Atlas redemande votre mot de passe : tapez-le, puis « Continuer ».",
    source: "src/app/reglages/identite/IdentiteClient.tsx",
    preuves: ["Pour être payé", 'etiquette="IBAN"', "Titulaire du compte"],
    ailleurs: [{ source: "src/components/atlas/DemanderPreuve.tsx", preuves: ["Vérifiez que c&apos;est bien vous"] }],
  },
  {
    id: "reglages-iban-prevenir",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, après un changement d'IBAN`,
    intitule: "Prévenir les clients dont la facture porte l'ancien IBAN",
    motsCles: ["iban", "ancien", "prevenir", "client", "facture", "changement", "banque", "sms"],
    geste: "Sur chaque facture listée, touchez « Prévenir », puis « Envoyer par SMS » ou « Par e-mail ».",
    reserve: "Seules les factures envoyées et pas encore réglées sont listées. « Plus tard » ferme l'écran sans rien envoyer.",
    source: "src/components/atlas/AlerteAncienIban.tsx",
    preuves: ["Prévenir", "Envoyer par SMS", "Par e-mail"],
    ailleurs: [{ source: "src/app/reglages/identite/IdentiteClient.tsx", preuves: ["Votre IBAN a changé", "Plus tard"] }],
  },
  {
    id: "reglages-decennale",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, bloc Assurance décennale`,
    intitule: "Renseigner son assurance décennale",
    motsCles: ["assurance", "decennale", "assureur", "contrat", "attestation", "couverture", "garantie"],
    geste: "Dans « Assurance décennale », remplissez « Assureur », « N° de contrat » et « Couverture géographique ».",
    reserve: "Sans assureur, vos devis partent sans une mention que la loi y attend.",
    source: "src/app/reglages/identite/IdentiteClient.tsx",
    preuves: ["Assurance décennale", 'etiquette="Assureur"', "N° de contrat", "Couverture géographique"],
  },
  {
    id: "reglages-mediateur",
    ecran: "Mon entreprise",
    ou: `${R}, puis Mon entreprise, bloc Médiateur de la consommation`,
    intitule: "Renseigner son médiateur de la consommation",
    motsCles: ["mediateur", "mediation", "consommation", "litige", "obligatoire", "particulier"],
    geste: "Dans « Médiateur de la consommation », écrivez son nom, puis son adresse ou son site.",
    reserve: "Obligatoire dès que vous travaillez pour des particuliers.",
    source: "src/app/reglages/identite/IdentiteClient.tsx",
    preuves: ["Médiateur de la consommation", 'etiquette="Adresse ou site"'],
  },
  {
    id: "reglages-preuve-mot-de-passe",
    ecran: "Réglages",
    ou: "une fenêtre « Vérifiez que c'est bien vous »",
    intitule: "Atlas me redemande mon mot de passe",
    motsCles: ["redemande", "verifiez", "bien", "vous", "passe", "securite", "confirmer", "pourquoi"],
    geste: "Tapez votre mot de passe, puis « Continuer ».",
    reserve: "Il est demandé pour changer l'IBAN, enregistrer ou retirer Face ID, et télécharger vos données.",
    source: "src/components/atlas/DemanderPreuve.tsx",
    preuves: ["Vérifiez que c&apos;est bien vous", "Votre mot de passe", '"Continuer"'],
  },
  // --- Devis & factures -----------------------------------------------------
  {
    id: "reglages-documents",
    ecran: "Ce qui s'imprime",
    ou: `${R}, puis Devis & factures, puis Ce qui s'imprime sur le devis`,
    intitule: "Régler la validité d'un devis, l'acompte, le délai de paiement",
    motsCles: ["validite", "acompte", "delai", "paiement", "jours", "pourcentage", "condition", "devis", "facture"],
    geste:
      "Ouvrez « Ce qui s'imprime sur le devis », allumez l'interrupteur de la ligne voulue, puis écrivez le chiffre : " +
      "« Durée de validité », « Acompte à la commande » ou « Délai de paiement ».",
    reserve: "Les documents déjà faits ne changent pas.",
    source: "src/app/reglages/documents/conditions/ConditionsClient.tsx",
    preuves: ["Durée de validité", "Acompte à la commande", "Délai de paiement"],
    ailleurs: [{ source: "src/lib/rubriques-reglages.ts", preuves: ["Ce qui s'imprime sur le devis"] }],
  },
  {
    id: "reglages-moyens-paiement",
    ecran: "Ce qui s'imprime",
    ou: `${R}, puis Devis & factures, puis Ce qui s'imprime sur le devis`,
    intitule: "Dire quels moyens de paiement j'accepte (virement, chèque, espèces)",
    motsCles: ["moyens", "paiement", "virement", "cheque", "especes", "accepte", "regler", "payer"],
    geste:
      "Allumez « Moyens de paiement acceptés », puis touchez « Virement et chèque », « Virement seulement » " +
      "ou « Virement, chèque, espèces ».",
    source: "src/app/reglages/documents/conditions/ConditionsClient.tsx",
    preuves: ["Moyens de paiement acceptés"],
    ailleurs: [{ source: "src/lib/modalites-paiement.ts", preuves: ["Virement et chèque", "Virement seulement", "Virement, chèque, espèces"] }],
  },
  {
    id: "reglages-penalites",
    ecran: "Ce qui s'imprime",
    ou: `${R}, puis Devis & factures, puis Ce qui s'imprime sur le devis`,
    intitule: "Afficher les pénalités de retard sur le devis",
    motsCles: ["penalites", "retard", "indemnite", "40", "rappeler", "devis", "mentions"],
    geste: "Allumez « Rappeler les pénalités sur le devis ».",
    reserve: "Sur la facture, elles s'impriment toujours : elles ne se coupent pas.",
    source: "src/app/reglages/documents/conditions/ConditionsClient.tsx",
    preuves: ["Rappeler les pénalités sur le devis", "Mentions légales de la facture"],
  },
  {
    id: "reglages-texte-pied",
    ecran: "Ce qui s'imprime",
    ou: `${R}, puis Devis & factures, puis Ce qui s'imprime sur le devis`,
    intitule: "Ajouter un texte en bas de tous mes devis",
    motsCles: ["texte", "bas", "pied", "phrase", "ajouter", "remarque", "reserve", "mention", "documents"],
    geste: "Allumez « Texte en bas de vos documents » et écrivez votre phrase dans la case.",
    source: "src/app/reglages/documents/conditions/ConditionsClient.tsx",
    preuves: ["Texte en bas de vos documents", "Sous réserve d'accès au chantier."],
  },
  {
    id: "reglages-cgv",
    ecran: "Ce qui s'imprime",
    ou: `${R}, puis Devis & factures, puis Ce qui s'imprime sur le devis`,
    intitule: "Mettre ses conditions générales de vente sur le devis",
    motsCles: ["cgv", "conditions", "generales", "vente", "reglement", "contrat", "imprimer", "devis"],
    geste:
      "Allumez « Conditions générales de vente et de règlement » : un texte est proposé, corrigez-le dans la case.",
    reserve: "Les crochets restants se remplissent depuis Mon entreprise. Elles s'impriment après le bon pour accord.",
    source: "src/app/reglages/documents/conditions/ConditionsClient.tsx",
    preuves: ["Conditions générales de vente et de règlement", "Imprimées après le bon pour accord", "à remplir dans Mon entreprise."],
  },
  {
    id: "reglages-message-client",
    ecran: "Mon message au client",
    ou: `${R}, puis Devis & factures, puis Mon message au client`,
    intitule: "Changer le message qui part avec un devis, une facture ou un retour d'intervention",
    motsCles: ["message", "texte", "envoi", "envoye", "sms", "mail", "accompagne", "modifier", "changer", "politesse"],
    geste:
      "Ouvrez « Mon message au client », corrigez le texte sous le document voulu, puis « Enregistrer ». " +
      "« Remettre le message d'Atlas » revient au texte d'origine.",
    reserve: "Les mots en doré se remplissent seuls. Le lien et le mot du document ne peuvent pas être retirés.",
    source: "src/app/reglages/documents/message/MessagesClient.tsx",
    preuves: ["Ce que j'envoie avec un devis", "Ce que j'envoie avec une facture", "Remettre le message d&apos;Atlas"],
    ailleurs: [{ source: "src/components/atlas/BarreEnregistrer.tsx", preuves: ['"Enregistrer"'] }],
  },
  {
    id: "reglages-numero",
    ecran: "Le numéro de mes documents",
    ou: `${R}, puis Devis & factures, puis Le numéro de mes documents`,
    intitule: "Choisir la forme du numéro des devis et des factures",
    motsCles: ["numero", "numerotation", "format", "annee", "compteur", "facture", "devis", "chiffres"],
    geste: "Ouvrez « Le numéro de mes documents » et touchez la forme voulue, par exemple « Année et 4 chiffres ».",
    reserve: "Vos documents déjà émis gardent leur numéro.",
    source: "src/app/reglages/documents/numero/NumeroClient.tsx",
    preuves: ["Vos documents déjà émis gardent leur numéro.", "Ce que ça donne"],
    ailleurs: [{ source: "src/lib/numero-documents.ts", preuves: ['nom: "Année et 4 chiffres"'] }],
  },
  {
    id: "reglages-logo",
    ecran: "L'allure de mes devis",
    ou: `${R}, puis Devis & factures, puis L'allure de mes devis`,
    intitule: "Mettre, changer ou retirer son logo sur les devis et factures",
    motsCles: ["logo", "image", "marque", "entete", "mettre", "changer", "retirer", "ajouter"],
    geste: "Touchez « Choisir une image ». Un logo déjà posé se remplace par « Changer » ou s'enlève par « Retirer ».",
    reserve: "PNG ou JPEG, 1,5 Mo au plus.",
    source: "src/app/reglages/documents/allure/AllureClient.tsx",
    preuves: ["Choisir une image", '"Changer"', "Retirer", "PNG ou JPEG, 1,5 Mo au plus."],
  },
  {
    id: "reglages-allure-couleurs",
    ecran: "L'allure de mes devis",
    ou: `${R}, puis Devis & factures, puis L'allure de mes devis`,
    intitule: "Changer la police et les couleurs de mes devis et factures",
    motsCles: ["police", "ecriture", "couleur", "fond", "accent", "allure", "devis", "facture", "style"],
    geste:
      "Touchez la police voulue, puis choisissez le « Fond de page » et la « Couleur d'accent ». " +
      "« Revenir aux réglages d'aujourd'hui » annule tout.",
    reserve: "Tout s'enregistre au fur et à mesure.",
    source: "src/app/reglages/documents/allure/AllureClient.tsx",
    preuves: ['titre="Fond de page"', "titre=\"Couleur d'accent\"", "Revenir aux réglages d&apos;aujourd&apos;hui"],
  },
  // --- Équipe ---------------------------------------------------------------
  {
    id: "reglages-donner-acces",
    ecran: "Équipe",
    ou: `${R}, puis Équipe`,
    intitule: "Ajouter un salarié, lui donner un accès à Atlas",
    motsCles: ["ajouter", "salarie", "salaries", "employe", "ouvrier", "acces", "inviter", "compte", "gars"],
    geste:
      "Ouvrez « Équipe », puis « Donner un accès ». Remplissez nom, adresse e-mail, mot de passe et sa confirmation, " +
      "choisissez le rôle, puis « Créer le compte ».",
    source: "src/app/reglages/equipe/QuiAAcces.tsx",
    preuves: ['href="/reglages/equipe/nouveau"', "Donner un accès"],
    ailleurs: [
      {
        source: "src/app/reglages/equipe/nouveau/NouveauCompte.tsx",
        preuves: ['etiquette="Adresse e-mail"', 'etiquette="Confirmer le mot de passe"', "Créer le compte"],
      },
    ],
  },
  {
    id: "reglages-role",
    ecran: "Équipe",
    ou: `${R}, puis Équipe, Accès`,
    intitule: "Changer le rôle d'une personne (patron, facturation, commercial, salarié)",
    motsCles: ["role", "droits", "permission", "facturation", "commercial", "salarie", "patron", "changer"],
    geste: "Dans « Accès », touchez la personne, puis le rôle voulu : Patron, Facturation, Commercial ou Salarié.",
    reserve: "Sous les rôles, la liste dit ce que ce rôle peut faire et ce qu'il ne peut plus.",
    source: "src/app/reglages/equipe/QuiAAcces.tsx",
    preuves: ["Accès", "<ChoixRole"],
    ailleurs: [
      { source: "src/app/reglages/equipe/ChoixRole.tsx", preuves: ["libelleRole(r)"] },
      { source: "src/lib/acces-roles.ts", preuves: ['return "Patron"', 'return "Facturation"', 'return "Commercial"', 'return "Salarié"'] },
    ],
  },
  {
    id: "reglages-portee-planning",
    ecran: "Équipe",
    ou: `${R}, puis Équipe, Accès`,
    intitule: "Choisir ce qu'un salarié voit du planning",
    motsCles: ["salarie", "planning", "equipe", "tout", "sienne", "limiter", "cacher", "portee"],
    geste: "Touchez le salarié dans « Accès », puis « Tout le planning » ou « Son équipe » et choisissez laquelle.",
    reserve: "Ne s'affiche que pour une personne au rôle Salarié.",
    source: "src/app/reglages/equipe/QuiAAcces.tsx",
    preuves: ["Ce qu&apos;il voit du planning", "Tout le planning", "Son équipe"],
  },
  {
    id: "reglages-retirer-acces",
    ecran: "Équipe",
    ou: `${R}, puis Équipe, Accès`,
    intitule: "Retirer l'accès d'un salarié qui part",
    motsCles: ["retirer", "supprimer", "enlever", "acces", "salarie", "depart", "bloquer", "compte"],
    geste: "Dans « Accès », touchez la personne, puis « Retirer l'accès ».",
    reserve: "Impossible sur votre propre compte.",
    source: "src/app/reglages/equipe/QuiAAcces.tsx",
    preuves: ["Retirer l&apos;accès", "!estMoi"],
  },
  {
    id: "reglages-nombre-chantiers",
    ecran: "Équipe",
    ou: `${R}, puis Équipe`,
    intitule: "Régler combien de chantiers partent le même jour",
    motsCles: ["combien", "chantiers", "jour", "equipes", "meme", "temps", "parallele", "nombre"],
    geste: "Sous « Combien de chantiers par jour », touchez « + » ou « − ».",
    source: "src/app/reglages/VosEquipes.tsx",
    preuves: ["Combien de chantiers par jour", "Une équipe de plus", "Une équipe de moins"],
  },
  {
    id: "reglages-salaries",
    ecran: "Équipe",
    ou: `${R}, puis Équipe`,
    intitule: "Dire combien j'ai de salariés et leur donner un nom",
    motsCles: ["salaries", "salarie", "nombre", "nom", "prenom", "nommer", "ouvriers", "combien"],
    geste: "Sous « Combien de salariés », touchez « + » ou « − », puis écrivez le nom de chacun sur sa ligne.",
    source: "src/app/reglages/VosSalaries.tsx",
    preuves: ["Combien de salariés", "Un salarié de plus", "Nom du salarié"],
  },
  {
    id: "reglages-absence",
    ecran: "Équipe",
    ou: `${R}, puis Équipe, bloc Absences`,
    intitule: "Noter l'absence d'un salarié (congé, arrêt, déplacement)",
    motsCles: ["absence", "absent", "conge", "conges", "vacances", "arret", "maladie", "noter", "indisponible"],
    geste:
      "Touchez « + Noter une absence », choisissez qui, le premier et le dernier jour, puis « Noter l’absence ». " +
      "Pour l'effacer, touchez la croix sur sa ligne.",
    reserve:
      "Il faut au moins un salarié : seul, posez vos congés dans votre agenda relié. " +
      "Les absences demandent la formule Entreprise.",
    source: "src/app/reglages/AbsencesEquipe.tsx",
    preuves: ["+ Noter une absence", "Noter l’absence", "Retirer l'absence de", "reliez votre agenda"],
    ailleurs: [{ source: "src/app/reglages/equipe/page.tsx", preuves: ['<FonctionReservee fonction="absences" />'] }],
  },
  {
    id: "reglages-fin-chantier",
    ecran: "Équipe",
    ou: `${R}, puis Équipe, bloc Fin de chantier`,
    intitule: "Rappeler aux salariés d'envoyer le retour d'intervention chaque soir",
    motsCles: ["fin", "chantier", "preuve", "photo", "retour", "cocher", "exiger", "obliger", "rappeler", "oubli", "recu"],
    geste: "Dans « Fin de chantier », allumez « Demander une preuve », puis si besoin « Au moins une photo ».",
    reserve: "Le salarié voit « Retour à envoyer » sous le chantier du jour ; vous, « Retour pas reçu » sur l'accueil le lendemain. Le retour part quand même. N'apparaît qu'avec la formule Entreprise.",
    source: "src/app/reglages/equipe/FinDeChantierReglage.tsx",
    preuves: ["Fin de chantier", "Demander une preuve", "Au moins une photo"],
  },
  // --- Notifications ----------------------------------------------------------
  {
    id: "reglages-rappel-relance",
    ecran: "Notifications",
    ou: `${R}, puis Notifications, ligne Facture impayée`,
    intitule: "Être relancé chaque jour ou chaque semaine pour une facture impayée",
    motsCles: ["impaye", "impayee", "relance", "redire", "rappel", "facture", "semaine", "frequence"],
    geste:
      "Allumez « Facture impayée », réglez le nombre de jours après l'échéance, puis sous « Puis me le redire » " +
      "touchez « Chaque jour », « Chaque semaine » ou « Tous les 15 jours ».",
    reserve: "Le rappel s'arrête dès que le règlement est noté.",
    source: "src/app/reglages/notifications/NotificationsClient.tsx",
    preuves: ["Facture impayée", "Puis me le redire", "Au bout de"],
    ailleurs: [{ source: "src/lib/rappels.ts", preuves: ['"Chaque jour"', '"Chaque semaine"', '"Tous les 15 jours"'] }],
  },
  {
    id: "reglages-rappel-couper",
    ecran: "Notifications",
    ou: `${R}, puis Notifications`,
    intitule: "Couper ou allumer un rappel (chantier sans devis, devis sans réponse, pas facturé)",
    motsCles: ["couper", "desactiver", "eteindre", "rappel", "notification", "devis", "reponse", "facture", "arreter"],
    geste: "Touchez l'interrupteur à droite du rappel. Allumé, réglez « Au bout de » en jours.",
    reserve: "La réponse d'un client à un devis et le lien de devis expiré sont toujours signalés.",
    source: "src/app/reglages/notifications/NotificationsClient.tsx",
    preuves: ["Chantier sans devis", "Devis sans réponse", "Chantier fini, pas facturé", 'role="switch"'],
  },
  // --- Mon agenda -------------------------------------------------------------
  {
    id: "reglages-agenda",
    ecran: "Mon agenda",
    ou: `${R}, puis Mon agenda`,
    intitule: "Relier son agenda Google",
    motsCles: ["agenda", "calendrier", "google", "relier", "connecter", "brancher", "synchroniser", "doublon"],
    geste:
      "Ouvrez « Mon agenda ». La première fois, touchez « Coller mes identifiants Google », collez-les, puis « Enregistrer ». " +
      "Touchez ensuite « Relier mon agenda Google » et acceptez chez Google.",
    reserve:
      "Réservé au patron. Sans agenda relié, Atlas ne voit pas les rendez-vous notés ailleurs et peut proposer ce jour-là.",
    source: "src/app/reglages/agenda/AgendaClient.tsx",
    preuves: ["Coller mes identifiants Google", "Relier mon agenda Google", "Enregistrer"],
  },
  {
    id: "reglages-agenda-pause",
    ecran: "Mon agenda",
    ou: `${R}, puis Mon agenda`,
    intitule: "Mettre en pause ou débrancher son agenda",
    motsCles: ["pause", "debrancher", "deconnecter", "agenda", "arreter", "reprendre", "effacer", "calendrier"],
    geste:
      "Touchez « Mettre en pause », puis « Reprendre la lecture » pour repartir. " +
      "Pour le détacher : « Débrancher et effacer », puis « Débrancher ».",
    source: "src/app/reglages/agenda/AgendaClient.tsx",
    preuves: ["Mettre en pause", "Reprendre la lecture", "Débrancher et effacer", "Débrancher"],
    ailleurs: [{ source: "src/app/reglages/agenda/AgendaAppleClient.tsx", preuves: ["Mettre en pause", "Débrancher et effacer"] }],
  },
  {
    id: "reglages-agenda-apple",
    ecran: "Mon agenda",
    ou: `${R}, puis Mon agenda, bloc iCloud`,
    intitule: "Relier son agenda Apple, iCloud",
    motsCles: ["agenda", "calendrier", "apple", "icloud", "iphone", "relier", "connecter", "synchroniser"],
    geste:
      "Sur account.apple.com, créez un mot de passe pour les apps. Dans « Mon agenda », écrivez votre adresse iCloud " +
      "et ce mot de passe, puis « Relier mon agenda Apple ».",
    reserve: "Réservé au patron.",
    source: "src/app/reglages/agenda/AgendaAppleClient.tsx",
    preuves: ["Relier mon agenda Apple", "Votre adresse iCloud", "Mot de passe pour les apps", "account.apple.com"],
  },
  {
    id: "reglages-agenda-apple-ecrire",
    ecran: "Mon agenda",
    ou: `${R}, puis Mon agenda, bloc iCloud`,
    intitule: "Faire apparaître ses chantiers dans le calendrier de l'iPhone",
    motsCles: ["chantiers", "calendrier", "iphone", "apple", "ecrire", "apparaitre", "agenda", "renvoyer"],
    geste:
      "Allumez « Écrire mes chantiers dans mon agenda » et touchez le calendrier voulu. " +
      "« Renvoyer mes chantiers dans l'agenda » les remet tous.",
    reserve: "Il faut d'abord avoir relié l'agenda Apple. Atlas ne touche jamais un rendez-vous qu'il n'a pas posé.",
    source: "src/app/reglages/agenda/AgendaAppleClient.tsx",
    preuves: ["Écrire mes chantiers dans mon agenda", "Dans quel calendrier", "Renvoyer mes chantiers dans l&apos;agenda"],
  },
  // --- Atlas IA ---------------------------------------------------------------
  {
    id: "reglages-atlas-ia",
    ecran: "Atlas IA",
    ou: `${R}, puis Atlas IA`,
    intitule: "Voir ce que l'IA d'Atlas sait faire aujourd'hui",
    motsCles: ["ia", "intelligence", "artificielle", "sait", "marche", "dictee", "branchee", "fonctionne"],
    geste: "Ouvrez « Atlas IA » : chaque ligne dit « Oui » ou « Pas encore ».",
    reserve: "Réservé au patron. Rien à faire de votre côté pour ce qui n'est pas encore branché.",
    source: "src/app/reglages/ia/page.tsx",
    preuves: ["Ce qu&apos;Atlas sait faire", '"Pas encore"'],
    lieu: true,
  },
  {
    id: "vocabulaire-regles",
    ecran: "Mon vocabulaire",
    ou: `${R}, puis Atlas IA, puis Mon vocabulaire`,
    intitule: "Poser un mot ou une règle que l'IA doit suivre",
    motsCles: ["regle", "regles", "ia", "consigne", "vocabulaire", "habitude", "toujours", "mot"],
    geste:
      "Touchez « Un mot » ou « Une règle », remplissez l'intitulé et « Ce que ça veut dire », puis « Ajouter ». " +
      "Sur une ligne, « Mettre de côté » la suspend et « Supprimer » l'efface.",
    reserve: "Réservé à l'éditeur d'Atlas. Vos propres mots se règlent dans Tarifs & catalogue, Le catalogue.",
    source: "src/app/reglages/vocabulaire/VocabulaireClient.tsx",
    preuves: ["Mes règles", "Une règle", "Ce que ça veut dire", "Mettre de côté", "Supprimer"],
    ailleurs: [{ source: "src/app/reglages/vocabulaire/page.tsx", preuves: ["Réservé à l'éditeur"] }],
  },
  // --- Mes données, abonnement --------------------------------------------------
  {
    id: "reglages-donnees",
    ecran: "Mes données",
    ou: `${R}, puis Mes données`,
    intitule: "Télécharger toutes ses données, en garder une copie",
    motsCles: ["donnee", "donnees", "export", "telecharger", "sauvegarde", "copie", "rgpd", "fichier"],
    geste: "Ouvrez « Mes données », puis « Télécharger mes données ».",
    reserve: "Atlas peut redemander votre mot de passe. Le fichier porte les coordonnées de vos clients.",
    source: "src/app/reglages/donnees/BoutonTelecharger.tsx",
    preuves: ["Télécharger mes données", "<DemanderPreuve"],
  },
  {
    id: "reglages-effacer-compte",
    ecran: "Mes données",
    ou: `${R}, puis Mes données, en bas`,
    intitule: "Effacer son compte Atlas",
    motsCles: ["effacer", "supprimer", "compte", "fermer", "desinscrire", "quitter", "resilier", "definitivement"],
    geste: "Ouvrez « Mes données » : l'adresse à qui écrire pour effacer votre compte est en bas.",
    reserve: "L'effacement ne se fait pas encore depuis l'application.",
    source: "src/app/reglages/donnees/page.tsx",
    preuves: ["Pour effacer votre compte, écrivez à", "CONTACT_ATLAS"],
  },
  {
    id: "reglages-abonnement",
    ecran: "Abonnement",
    ou: `${R}, puis Abonnement`,
    intitule: "Changer de carte, voir ses factures Atlas, résilier",
    motsCles: ["abonnement", "carte", "bancaire", "facture", "atlas", "resilier", "arreter", "gerer"],
    geste: "Ouvrez « Abonnement », puis « Gérer mon abonnement ».",
    reserve: "Réservé au patron, et seulement une fois abonné. Les factures de vos clients sont dans « Terminés ».",
    source: "src/app/reglages/abonnement/AbonnementClient.tsx",
    preuves: ["Gérer mon abonnement", "Changer de carte, vos factures Atlas, résilier."],
  },
  {
    id: "reglages-formule",
    ecran: "Abonnement",
    ou: `${R}, puis Abonnement`,
    intitule: "S'abonner ou changer de formule, payer au mois ou à l'année",
    motsCles: ["formule", "abonner", "offre", "entreprise", "prix", "annuel", "mois", "annee", "changer"],
    geste:
      "Ouvrez « Abonnement », choisissez « Au mois » ou « À l’année, 2 mois offerts », " +
      "puis « S’abonner » ou « Passer à cette formule » sous la formule voulue.",
    reserve: "Réservé au patron.",
    source: "src/app/reglages/abonnement/AbonnementClient.tsx",
    preuves: ["Au mois", "À l’année, 2 mois offerts", "S’abonner", "Passer à cette formule"],
  },
  // --- Moi ----------------------------------------------------------------------
  {
    id: "reglages-compte",
    ecran: "Mon compte",
    ou: `${R}, puis Mon compte`,
    intitule: "Changer son prénom, son nom ou sa civilité",
    motsCles: ["compte", "nom", "prenom", "civilite", "madame", "monsieur", "moi", "profil", "changer"],
    geste: "Ouvrez « Mon compte », corrigez la civilité, le prénom ou le nom, puis « Enregistrer ».",
    reserve: "L'e-mail sert à vous connecter et ne se modifie pas encore.",
    source: "src/app/reglages/compte/CompteClient.tsx",
    preuves: ["Qui vous êtes", "Civilité", 'aria-label="Prénom"', "Pas encore modifiable."],
    ailleurs: [{ source: "src/components/atlas/BarreEnregistrer.tsx", preuves: ['"Enregistrer"'] }],
  },
  {
    id: "reglages-mot-de-passe",
    ecran: "Mot de passe",
    ou: `${R}, puis Mot de passe`,
    intitule: "Changer son mot de passe",
    motsCles: ["mot", "passe", "motdepasse", "changer", "securite", "connexion", "nouveau"],
    geste:
      "Ouvrez « Mot de passe », écrivez l'actuel, le nouveau et sa confirmation, puis « Changer mon mot de passe ».",
    source: "src/app/reglages/connexion/ConnexionClient.tsx",
    preuves: ["Mot de passe actuel", "Nouveau mot de passe", "Changer mon mot de passe"],
    ailleurs: [{ source: "src/lib/rubriques-reglages.ts", preuves: ['nom: "Mot de passe"'] }],
  },
  {
    id: "reglages-face-id",
    ecran: "Mot de passe",
    ou: `${R}, puis Mot de passe`,
    intitule: "Ouvrir Atlas avec Face ID",
    motsCles: ["face", "id", "faceid", "empreinte", "biometrie", "ouvrir", "connexion", "rapide", "touch"],
    geste: "Ouvrez « Mot de passe », puis « Enregistrer cet appareil » sous « Ouvrir avec Face ID ».",
    reserve:
      "Votre mot de passe reste actif, et c'est à faire sur chaque appareil. " +
      "Le bloc n'apparaît que sur un appareil qui sait le faire.",
    source: "src/app/reglages/connexion/SectionFaceId.tsx",
    preuves: ["Ouvrir avec Face ID", "Enregistrer cet appareil"],
  },
  {
    id: "reglages-face-id-retirer",
    ecran: "Mot de passe",
    ou: `${R}, puis Mot de passe, bloc Ouvrir avec Face ID`,
    intitule: "Retirer Face ID d'un appareil",
    motsCles: ["face", "faceid", "retirer", "supprimer", "enlever", "appareil", "telephone", "ancien"],
    geste: "Sous « Ouvrir avec Face ID », touchez « Retirer » à côté de l'appareil.",
    reserve: "Votre mot de passe marche toujours. Atlas peut vous le redemander avant.",
    source: "src/app/reglages/connexion/SectionFaceId.tsx",
    preuves: ["Ouvrir avec Face ID", "Retirer", "retirerCleAction"],
  },
  {
    id: "reglages-deconnexion-partout",
    ecran: "Mot de passe",
    ou: `${R}, puis Mot de passe, en bas`,
    intitule: "Se déconnecter de tous ses appareils (téléphone perdu)",
    motsCles: ["deconnexion", "partout", "perdu", "vole", "telephone", "appareils", "tous", "session"],
    geste: "Ouvrez « Mot de passe », touchez « Me déconnecter partout », puis encore « Me déconnecter partout » pour confirmer.",
    reserve: "Celui-ci compris : vous devrez vous reconnecter, et Face ID sera retiré.",
    source: "src/app/reglages/connexion/ConnexionClient.tsx",
    preuves: ["Me déconnecter partout", "celui-ci compris", "Face ID sera retiré de vos appareils."],
  },
  {
    id: "reglages-apparence",
    ecran: "Couleurs",
    ou: `${R}, puis Couleurs`,
    intitule: "Changer les couleurs de l'application, passer en sombre",
    motsCles: ["couleur", "couleurs", "charte", "apparence", "sombre", "nuit", "theme", "clair", "mode", "fond"],
    geste: "Ouvrez « Couleurs » et touchez la charte voulue. « Nuit » et « Sylve » sont sombres.",
    reserve: "Vos devis et factures ne changent pas de couleur.",
    source: "src/app/reglages/apparence/ApparenceClient.tsx",
    preuves: ["Votre charte"],
    ailleurs: [
      { source: "src/lib/chartes.ts", preuves: ['libelle: "Nuit"', 'libelle: "Sylve"'] },
      { source: "src/lib/rubriques-reglages.ts", preuves: ['nom: "Couleurs"'] },
    ],
  },
  // --- L'assistant ----------------------------------------------------------------
  {
    id: "assistant-ecrire",
    ecran: "Assistant",
    ou: "la pastille ronde en haut à droite de l'écran",
    intitule: "Poser une question écrite à l'assistant",
    motsCles: ["assistant", "question", "ecrire", "demander", "taper", "envoyer", "aide"],
    geste: "Ouvrez l'assistant, écrivez dans « Votre question… », puis touchez la flèche d'envoi.",
    source: "src/components/atlas/AssistantSidebar.tsx",
    preuves: ['placeholder="Votre question…"', 'aria-label="Envoyer"'],
  },
  {
    id: "assistant-dicter",
    ecran: "Assistant",
    ou: "l'assistant, à gauche du champ de question",
    intitule: "Poser sa question à l'assistant à la voix",
    motsCles: ["dicter", "dictee", "micro", "voix", "parler", "vocal", "oral", "assistant"],
    geste:
      "Touchez le micro et parlez. Touchez ensuite l'envoi à droite pour poser la question, " +
      "ou la corbeille à gauche pour jeter ce que vous avez dit.",
    reserve: "Si le micro ne marche pas, autorisez-le dans votre navigateur.",
    source: "src/components/atlas/AssistantSidebar.tsx",
    preuves: ['aria-label="Dicter la question"', 'aria-label="Envoyer la dictée"', 'aria-label="Jeter la dictée"'],
  },
  {
    id: "assistant-photo",
    ecran: "Assistant",
    ou: "l'assistant, à gauche du champ de question",
    intitule: "Montrer une photo à l'assistant",
    motsCles: ["photo", "image", "montrer", "assistant", "regarder", "appareil", "photographier", "voit"],
    geste:
      "Touchez l'appareil photo, prenez ou choisissez la photo. Quand « Photo lue » s'affiche, " +
      "posez votre question ou envoyez tel quel. « Retirer » l'enlève.",
    source: "src/components/atlas/AssistantSidebar.tsx",
    preuves: ['aria-label="Montrer une photo"', "Photo lue, elle part avec votre question.", "Retirer"],
  },
  {
    id: "assistant-oublier",
    ecran: "Assistant",
    ou: "l'assistant, en haut",
    intitule: "Effacer la conversation avec l'assistant, repartir de zéro",
    motsCles: ["oublier", "effacer", "vider", "conversation", "historique", "fil", "assistant", "recommencer"],
    geste: "En haut de l'assistant, touchez « Oublier ».",
    reserve: "Le mot n'apparaît que s'il y a déjà des messages.",
    source: "src/components/atlas/AssistantSidebar.tsx",
    preuves: ["Oublier", "viderFilAction"],
  },
  {
    id: "assistant-propositions",
    ecran: "Assistant",
    ou: "l'assistant, sous sa réponse",
    intitule: "Valider ou refuser les modifications proposées par l'assistant",
    motsCles: ["appliquer", "valider", "propositions", "modifications", "cocher", "decocher", "refuser", "assistant"],
    geste:
      "Décochez ce que vous ne voulez pas, puis « Appliquer les modifications ». « Annuler » n'applique rien.",
    reserve: "Rien n'est modifié tant que vous n'avez pas appuyé sur « Appliquer les modifications ».",
    source: "src/components/atlas/AssistantSidebar.tsx",
    preuves: ['type="checkbox"', "Appliquer les modifications", "Annuler"],
  },
  {
    id: "assistant-fermer",
    ecran: "Assistant",
    ou: "l'assistant, en haut à droite",
    intitule: "Fermer l'assistant",
    motsCles: ["fermer", "assistant", "quitter", "masquer", "sortir", "croix"],
    geste: "Touchez la croix en haut à droite de l'assistant, ou de nouveau la pastille ronde.",
    source: "src/components/atlas/AssistantSidebar.tsx",
    preuves: ['aria-label="Fermer"'],
    ailleurs: [{ source: "src/components/atlas/BoutonAssistant.tsx", preuves: ["Fermer l'assistant"] }],
  },
  // --- Réglages : l'entreprise ---------------------------------------------
  {
    id: "reglages-identite",
    ecran: "Mon entreprise",
    ou: "Réglages, puis Mon entreprise",
    intitule: "Changer le nom, l'adresse, le SIRET, l'IBAN de l'entreprise",
    motsCles: ["entreprise", "identite", "nom", "adresse", "siret", "iban", "tva", "coordonnees", "siege"],
    geste: "Ouvrez « Mon entreprise », corrigez le champ, puis « Enregistrer ».",
    reserve: "Ces informations figurent en tête de chaque devis et de chaque facture.",
    source: "src/app/reglages/identite/IdentiteClient.tsx",
    preuves: ["Nom de l'entreprise", "Adresse du siège", "Enregistrer"],
  },
  {
    id: "reglages-grilles",
    ecran: "Mes prix",
    ou: "Réglages, puis Tarifs & catalogue, puis Mes prix",
    intitule: "Régler un prix qui dépend du diamètre ou de la façon de faire",
    motsCles: ["grille", "diametre", "abattage", "cable", "facon", "travail", "prix", "mesure", "bareme"],
    geste: "Appuyez sur « Ajouter un travail », nommez-le, et choisissez comment son prix se décide.",
    source: "src/app/reglages/prix/GrillesPrixClient.tsx",
    preuves: ["Ajouter un travail", "Comment son prix se décide"],
  },
  {
    id: "reglages-allure-photo",
    // **L'écran a été coupé en quatre le 7 septembre 2026** : « Devis &
    // factures » n'est plus qu'un sommaire, et l'allure vit dans sa propre
    // page. La fiche pointait encore le fichier disparu — un mode d'emploi qui
    // enseigne un geste mort est pire qu'une page vide, puisqu'on le suit.
    ecran: "L'allure de mes devis",
    ou: "Réglages, puis Devis & factures, puis L'allure de mes devis",
    intitule: "Reprendre l'allure de son ancien devis en le photographiant",
    motsCles: ["photo", "photographier", "allure", "couleur", "police", "logo", "devis", "reprendre", "modele"],
    geste: "Ouvrez « L’allure de mes devis », appuyez sur « Photographier mon devis » et choisissez l'appareil photo ou la photothèque.",
    reserve: "L'allure et les mentions sont reprises ; ni les lignes, ni les prix, ni le logo.",
    source: "src/app/reglages/documents/allure/AllureClient.tsx",
    preuves: ["Photographier mon devis"],
  },
  {
    id: "reglages-equipe",
    ecran: "Équipe",
    ou: "Réglages, puis Équipe",
    // **Deux réglages distincts depuis le 26 août 2026** (`ARCHITECTURE.md`
    // §192) : combien de chantiers partent en même temps, et combien de gens
    // travaillent avec lui. Les confondre dans la réponse de l'assistant
    // remettrait dans sa tête la confusion qu'on vient de retirer du code.
    intitule: "Régler combien de chantiers partent en même temps, vos salariés et leurs absences",
    motsCles: ["equipe", "equipes", "salarie", "salaries", "nom", "prenom", "gars", "absence", "conge", "vacances", "combien", "partent"],
    geste: "Ouvrez « Équipe » : le nombre de chantiers menés en même temps, vos salariés et leurs absences s'y règlent.",
    source: "src/lib/rubriques-reglages.ts",
    preuves: ["Équipe"],
  },
  {
    id: "reglages-notifications",
    ecran: "Notifications",
    ou: "Réglages, puis Notifications",
    intitule: "Choisir ce qu'Atlas signale et quand",
    motsCles: ["notification", "notifications", "alerte", "rappel", "signaler", "relance", "impaye", "prevenir"],
    geste: "Ouvrez « Notifications » et réglez chaque rappel, ainsi que son délai.",
    reserve: "Deux alertes ne se coupent pas : la réponse à un devis et le lien de devis expiré.",
    source: "src/app/reglages/notifications/NotificationsClient.tsx",
    preuves: ["Ce qui vous est toujours signalé", "Ce que vous réglez"],
  },
  // --- L'assistant lui-même -------------------------------------------------
  {
    id: "assistant-ouvrir",
    ecran: "Assistant",
    ou: "l'en-tête de chaque écran",
    intitule: "Ouvrir l'assistant",
    motsCles: ["assistant", "aide", "question", "ouvrir", "bulle", "parler", "toi"],
    geste: "Appuyez sur la pastille ronde en haut à droite de l'écran.",
    source: "src/components/atlas/BoutonAssistant.tsx",
    preuves: ["Ouvrir l'assistant"],
  },
  {
    id: "assistant-copier-ligne",
    ecran: "Assistant",
    ou: "l'assistant, depuis un devis ouvert",
    intitule: "Reprendre une ligne du devis d'un autre client",
    motsCles: ["reprendre", "copier", "ligne", "devis", "autre", "client", "meme", "chercher", "poser"],
    geste:
      "Ouvrez le devis où poser la ligne, puis demandez à l'assistant, par exemple : " +
      "« reprends la ligne d'élagage du devis de Bernard ». Il la cherche, la propose, et vous la validez.",
    reserve: "Le montant est relu sur la ligne d'origine au moment où vous validez : rien n'est recopié de mémoire.",
    source: "src/server/ai/tools/rechercher-lignes-devis.ts",
    preuves: ["RechercherLignesDevis"],
  },
];
