/**
 * Les questions telles qu'un artisan les pose, et la fiche qui doit sortir
 * en tête. Une par fiche au moins : une fiche qu'aucune question ne retrouve
 * est une fiche que l'assistant ne récitera jamais.
 *
 * Un écart ne se corrige pas en changeant la question : on corrige les
 * mots-clés de la fiche, ou la recherche (`src/lib/mode-emploi.ts`).
 */
export const QUESTIONS_PAR_ZONE: Record<string, [string, string][]> = {
  // Les fiches d'avant le 24 septembre 2026, qu'aucune question ne visait.
  anciennes: [
    ["où sont mes chantiers en cours", "ecran-chantiers"],
    ["comment supprimer un chantier de la liste", "chantiers-retirer"],
    ["j'ai supprimé par erreur comment annuler", "chantiers-annuler-retrait"],
    ["comment reprendre un chantier là où je me suis arrêté", "chantiers-ouvrir"],
    ["comment compléter ma note vocale j'avais oublié quelque chose", "note-vocale-completer"],
    ["comment remplacer la note vocale", "note-vocale-remplacer"],
    ["j'ai un fichier audio comment l'envoyer", "note-vocale-fichier"],
    ["comment corriger le texte de la dictée", "transcription-corriger"],
    ["comment valider les informations du chantier", "informations-valider"],
    ["comment préparer le devis depuis les prix", "prix-preparer-devis"],
    ["comment retirer une ligne du devis", "devis-ligne-retirer"],
    ["comment voir l'aperçu du devis en pdf", "devis-apercu"],
    ["comment changer l'échéance de la facture", "facture-echeance"],
    ["comment voir la facture en pdf", "facture-pdf"],
    ["où sont les chantiers pas encore facturés", "termines-facturer"],
    ["comment poser un chantier sur un jour du planning", "planning-poser"],
    ["comment laisser une note sur une journée", "planning-note"],
    ["comment aller au chantier avec waze", "planning-itineraire"],
    ["comment voir la semaine suivante", "planning-semaine"],
    ["comment passer de la journée aux sept jours", "planning-journee-ou-semaine"],
    ["comment faire un diagnostic d'un arbre malade", "paysage-diagnostic"],
    ["comment régler mes grilles de prix", "reglages-grilles"],
    ["comment reprendre l'allure de mon devis en photo", "reglages-allure-photo"],
    ["combien de chantiers partent en même temps, où je règle ça", "reglages-equipe"],
    ["comment couper les notifications", "reglages-notifications"],
    ["comment ouvrir l'assistant", "assistant-ouvrir"],
    ["reprendre la ligne d'élagage du devis d'un autre client", "assistant-copier-ligne"],
  ],
  chantier: [
    ["comment je crée un nouveau devis", "chantiers-nouveau"],
    ["je veux fermer la fiche client sans perdre ce que j'ai tapé", "chantiers-fermer-fiche-client"],
    ["comment compléter l'adresse manquante d'un chantier", "chantiers-adresse-manquante"],
    ["comment savoir si le devis est envoyé ou à relancer", "chantiers-etat-ligne"],
    ["le client demande une correction du devis, je fais quoi", "chantiers-carte-correction"],
    ["le client a accepté le devis, je fais quoi", "chantiers-carte-accepte"],
    ["mon devis est caduc, comment le renvoyer", "chantiers-carte-refuse"],
    ["le client a confirmé avoir reçu la facture", "chantiers-carte-facture-recue"],
    ["facture impayée, j'ai reçu le paiement", "chantiers-carte-impayee"],
    ["j'ai un rappel à facturer, comment je fais", "chantiers-carte-rappels"],
    ["comment faire disparaître une carte notification", "chantiers-carte-j-ai-vu"],
    ["voir les autres cartes de notifications", "chantiers-cartes-toutes"],
    ["comment remplir le client d'un nouveau chantier", "nouveau-chantier-saisie"],
    ["je veux écrire mon devis à la main sans dicter", "chantier-rediger-main"],
    ["comment mettre madame au lieu de monsieur", "chantier-civilite"],
    ["mettre une adresse client différente du chantier", "chantier-adresse-client"],
    ["envoyer le devis par sms ou par mail", "chantier-envoi-canal"],
    ["reprendre un client déjà connu", "chantier-client-connu"],
    ["dicter le téléphone et l'adresse du client au micro", "chantier-dicter-coordonnees"],
    ["comment dicter une note vocale pour le devis", "fiche-note-vocale"],
    ["jeter la dictée à la poubelle pour recommencer", "chantier-dictee-jeter"],
    ["supprimer la dictée pour redicter", "chantier-dictee-retirer"],
    ["comment ajouter des photos au chantier", "photos-ajouter"],
    ["supprimer une photo du chantier", "chantier-photo-retirer"],
    ["voir les photos en grand", "chantier-photo-voir"],
    ["reprendre les anciennes photos de la dernière fois", "chantier-photos-derniere-fois"],
    ["faire une facture directe sans devis pour un client", "termines-creer-facture"],
    ["répondre aux questions avant de chiffrer", "devis-questions-chiffrage"],
    ["atlas n'a pas trouvé de prix, comment poser les prix", "chantier-devis-sans-prix"],
    ["repartir de la dictée ou conserver mes corrections", "chantier-dictee-conflit"],
    ["où est l'écran de la note vocale", "note-vocale-ou"],
    ["enregistrer une note vocale et l'arrêter", "note-vocale-enregistrer"],
    ["comment réécouter ma note vocale", "note-vocale-ecouter"],
    ["supprimer la note vocale", "note-vocale-retirer"],
    ["relancer la transcription de la note", "note-vocale-transcrire"],
    ["créer le devis à partir de la note vocale", "note-vocale-suite"],
    ["où je relis le texte de ma dictée", "transcription-ou"],
    ["passer de la transcription aux informations", "transcription-suite"],
    ["la transcription a échoué, que faire", "transcription-echec"],
    ["générer le brouillon depuis la dictée", "informations-brouillon-generer"],
    ["confirmer le brouillon entendu", "informations-brouillon-confirmer"],
    ["remplacer mes corrections par la nouvelle analyse", "informations-brouillon-conflit"],
    ["écrire les lignes à la main dans informations", "informations-a-la-main"],
    ["ajouter une prestation ou du matériel", "informations-prestations"],
    ["changer la durée et l'équipe", "informations-duree-equipe"],
    ["où noter les contraintes d'accès et les déchets", "informations-notes"],
    ["aller directement au devis depuis informations", "informations-ecrire-devis"],
    ["modifier le montant d'une ligne de prix", "prix-lignes"],
    ["ajouter la proposition de prix au détail", "prix-proposition"],
    ["le bouton préparer le devis est grisé, une ligne attend son prix", "prix-bloque"],
  ],
  devis: [
    ["comment je change la tva du devis", "devis-tva"],
    ["je veux mettre 10 % de tva", "devis-tva"],
    ["comment je propose une date au client", "devis-dates"],
    ["comment j'envoie le devis au client", "devis-envoyer"],
    ["je veux transmettre mon devis par sms", "devis-envoyer"],
    ["comment je modifie un devis deja envoye", "devis-corriger-envoye"],
    ["je me suis trompe sur un devis parti comment corriger", "devis-corriger-envoye"],
    ["comment telecharger le pdf du devis envoye", "devis-telecharger"],
    ["comment ajouter une ligne au devis", "devis-ligne-ajouter"],
    ["je veux rajouter une prestation sur le devis", "devis-ligne-ajouter"],
    ["comment je change la quantite d'une ligne", "devis-ligne-modifier"],
    ["comment mettre en metre lineaire ou en m2", "devis-unite"],
    ["mettre une ligne au forfait", "devis-unite"],
    ["une ligne est a chiffrer comment poser le prix", "devis-a-chiffrer"],
    ["pourquoi le bouton choisir la date a disparu, il manque un prix", "devis-a-chiffrer"],
    ["reprendre le prix de la derniere fois", "devis-reprendre-prix"],
    ["comment donner un titre au devis", "devis-titre"],
    ["comment mettre deux taux de tva sur un devis", "devis-plusieurs-tva"],
    ["comment deplacer une ligne vers l'autre tva", "devis-ligne-changer-tva"],
    ["comment supprimer une categorie de tva", "devis-retirer-tva"],
    ["ou je mets la main d'oeuvre pour le credit d'impot", "devis-main-doeuvre"],
    ["comment demander un acompte", "devis-acompte"],
    ["je veux 30 % d'acompte a la commande", "devis-acompte"],
    ["comment enlever la remise", "devis-remise-retirer"],
    ["comment corriger l'adresse du client sur le devis", "devis-client-coordonnees"],
    ["le devis n'a pas de client comment en mettre un", "devis-sans-client"],
    ["corriger l'adresse des travaux sur le devis", "devis-adresse-chantier"],
    ["changer le siret de mon entreprise sur le devis", "devis-entreprise"],
    ["ou mettre mon iban sur le devis", "devis-iban"],
    ["ajouter une note ou des conditions au devis", "devis-notes"],
    ["comment dicter une correction dans le devis au micro", "devis-dicter"],
    ["atlas me pose des questions avant de chiffrer", "devis-questions-chiffrage"],
    ["le devis est bloque je ne peux plus le modifier", "devis-fige"],
    ["comment proposer deux dates au client", "devis-deux-dates"],
    ["je ne veux pas que le client propose une autre date", "devis-autre-date-client"],
    ["changer la duree du chantier avant d'envoyer", "devis-duree-envoi"],
    ["comment savoir si l'equipe est libre ce jour la", "devis-jour-libre"],
    ["comment enlever un jour propose", "devis-date-effacer"],
    ["le client n'a pas de numero de telephone comment envoyer", "devis-envoi-coordonnee"],
    ["fermer l'envoi sans envoyer", "devis-envoi-annuler"],
    ["comment savoir si le client a accepte le devis", "devis-etat"],
    ["comment relancer un client qui ne repond pas", "devis-relancer"],
    ["envoyer par mail plutot que par sms", "devis-changer-canal"],
    ["le client a demande une correction que faire", "devis-correction-demandee"],
    ["le client a refuse le devis comment le reprendre", "devis-reprendre-refuse"],
    ["qu'est ce que le client voit quand il ouvre le devis", "devis-client-page"],
    ["comment le client accepte le devis", "devis-client-accepter"],
    ["le client peut il proposer une autre date", "devis-client-autre-date"],
    ["comment le client demande une correction", "devis-client-correction"],
    ["comment le client refuse le devis", "devis-client-refuser"],
    ["le client peut telecharger son devis", "devis-client-telecharger"],
    ["c'est quoi la case retractation 14 jours", "devis-client-retractation"],
    ["le client dit que le lien ne marche plus", "devis-client-lien-expire"],
  ],
  facture: [
    ["mon client ne me paiera jamais comment je range la facture", "il-ne-paiera-pas"],
    ["comment faire une mise en demeure", "mise-en-demeure"],
    ["comment je fais la facture d'un chantier fini", "facture-creer"],
    ["je veux facturer mon chantier", "facture-creer"],
    ["comment je mets un titre sur ma facture", "facture-titre"],
    ["j'ai renvoyé un devis corrigé, la facture a les anciens montants", "facture-reprendre-devis"],
    ["comment rajouter des travaux supplémentaires sur la facture", "facture-travaux-supplementaires"],
    ["où j'écris les lignes d'une facture sans devis", "facture-remplir-sans-devis"],
    ["comment mettre de la tva à 10 sur une ligne de la facture", "facture-lignes-tva"],
    ["comment supprimer les travaux supplémentaires", "facture-supplement-retirer"],
    ["comment j'indique la main d'oeuvre sur la facture", "facture-main-doeuvre"],
    ["comment faire une remise sur une facture", "facture-remise"],
    ["le client m'a versé un acompte, je le mets où sur la facture", "facture-reglement-recu"],
    ["comment je mets qu'il a payé par chèque et le numéro du chèque", "facture-moyen-paiement"],
    ["je veux écrire arrhes au lieu d'acompte", "facture-reglement-nommer"],
    ["comment enlever un règlement que j'ai mis par erreur sur la facture", "facture-reglement-retirer"],
    ["comment je mets facture acquittée", "facture-acquittee"],
    ["comment télécharger la facture sur mon téléphone", "facture-telecharger"],
    ["comment j'envoie la facture au client par sms", "facture-envoyer"],
    ["comment je renvoie une facture déjà envoyée par mail", "facture-renvoyer"],
    ["le client n'a pas de numéro, comment je lui envoie la facture", "facture-coordonnee-manquante"],
    ["comment je corrige une facture", "facture-modifier"],
    ["qu'est-ce que le client voit quand il ouvre le lien de la facture", "facture-page-client"],
    ["comment je sais si le client a ouvert sa facture", "facture-reception-client"],
    ["comment faire une facture pour un dépannage sans devis", "termines-creer-facture"],
    ["pourquoi mon chantier n'apparaît pas dans terminés", "termines-quand-apparait"],
    ["combien j'ai facturé sur ce chantier", "termines-montant"],
    ["comment voir les photos d'un retour d'intervention", "retours-lire"],
    ["chercher les retours d'un client", "retours-chercher"],
    ["voir les retours du mois dernier", "retours-date"],
    ["comment voir la tva du trimestre précédent", "tva-periode"],
    ["passer ma déclaration de tva en trimestrielle", "tva-rythme"],
    ["comment copier le montant de tva à payer", "tva-copier"],
    ["ça veut dire quoi crédit de tva", "tva-credit"],
    ["comment scanner un ticket de caisse", "tva-scanner-ticket"],
    ["ajouter un achat à la main pour la tva", "tva-achat-main"],
    ["où je vois les achats comptés dans la tva", "tva-detail"],
    ["comment je note qu'une facture est payée", "facture-payee"],
    ["le client a payé une partie, je le note où", "tva-paiement-partiel"],
    ["annuler un paiement noté par erreur", "tva-retirer-paiement"],
    ["voir toutes les factures impayées", "tva-toutes-en-attente"],
    ["j'ai changé d'iban, comment prévenir le client", "tva-ancien-iban"],
  ],
  planning: [
    ["comment je déplace un chantier à un autre jour", "planning-deplacer"],
    ["je veux décaler juste le matin d'un chantier", "planning-deplacer"],
    ["comment enlever un chantier du planning sans le supprimer", "planning-retirer"],
    ["comment je donne la feuille sans les prix à mes gars", "planning-feuille"],
    ["comment passer au mois suivant", "planning-mois"],
    ["comment je vois ce qui est posé un jour", "planning-ouvrir-jour"],
    ["que veulent dire les couleurs du calendrier", "planning-couleurs"],
    ["comment ajouter un nouveau client directement au planning sans devis", "planning-ajouter-un-client"],
    ["comment bloquer du temps pour la banque", "planning-ajouter-autre-chose"],
    ["comment je pose un client sans date", "planning-poser-depuis-le-bas"],
    ["je me suis trompé de jour en posant, comment annuler la pose", "planning-annuler-pose"],
    ["comment supprimer définitivement un chantier sans date", "planning-supprimer-sans-date"],
    ["comment reposer la demi journée qui attend", "planning-reposer-demi-journee"],
    ["où sont les clients qui choisissent leur date", "planning-attente-client"],
    ["comment je choisis quels salariés vont sur le chantier", "planning-equipe-cocher"],
    ["comment noter qu'un salarié est absent", "planning-absence"],
    ["comment enlever une absence mise par erreur", "planning-absence-retirer"],
    ["pourquoi mon salarié ne peut pas modifier le planning", "planning-salarie-lecture"],
    ["comment ouvrir la fiche client depuis le planning", "planning-portes"],
    ["comment facturer un chantier fini depuis le planning", "planning-facturer"],
    ["c'est quoi le bandeau agenda en pause en haut du planning", "planning-agenda-bandeau"],
    ["comment envoyer le retour d'intervention du soir", "planning-retour-du-jour"],
    ["comment reprendre la fiche de sécurité et passer à l'étape suivante", "fiche-securite-etapes"],
    ["comment relever la position gps du chantier", "fiche-securite-gps"],
    ["comment dire que le donneur d'ordre est un syndic", "fiche-securite-donneur"],
    ["comment ajouter mon propre matériel dans la fiche de sécurité", "fiche-securite-ajouter"],
    ["comment retirer la photo de la fiche de sécurité", "fiche-securite-photo"],
    ["quel numéro appeler en cas d'accident", "fiche-securite-secours"],
    ["comment signer la fiche de sécurité", "fiche-securite-signer"],
    ["comment envoyer la fiche de sécurité par whatsapp", "fiche-securite-transmettre"],
    ["comment voir le pdf de la fiche de sécurité", "fiche-securite-pdf"],
    ["comment corriger une fiche de sécurité déjà signée", "fiche-securite-modifier"],
  ],
  paysage: [
    ["comment je fais un plan d'arrosage", "paysage-arrosage"],
    ["je suis sur un robinet de jardin, je mets quoi comme pression", "arrosage-mesure-robinet"],
    ["ou je rentre le debit au seau", "arrosage-mesure-robinet"],
    ["il me refuse mon croquis, il manque la nourrice", "arrosage-croquis-refuse"],
    ["pourquoi il me dit le croquis ne sera pas lu", "arrosage-croquis-non-lu"],
    ["il y a combien de reseaux et quelle buse", "arrosage-reseaux"],
    ["c'est quoi les points rouges sous le plan", "arrosage-reserves"],
    ["le rond et le carre sur le plan ca veut dire quoi", "arrosage-legende"],
    ["a partir de combien de metres je passe en 32", "arrosage-diametre-tuyau"],
    ["ou est la liste des pieces a commander", "arrosage-liste-pieces"],
    ["comment je change la marque des arroseurs sur le plan", "arrosage-modifier-plan"],
    ["je peux faire une terrasse bois", "paysage-terrasse-bois"],
    ["ou je vois le traitement pour la maladie", "diagnostic-details"],
    ["comment je lie le diagnostic a un chantier", "diagnostic-rattacher"],
    ["je veux faire un autre diagnostic", "diagnostic-nouvelle-photo"],
    ["il me demande une deuxieme photo", "diagnostic-photo-de-plus"],
    ["le diagnostic est sans conclusion", "diagnostic-sans-conclusion"],
    ["la photo n'a pas ete regardee, je fais quoi", "diagnostic-echoue"],
    ["comment j'ouvre le pdf de la fiche de securite", "securite-ouvrir-pdf"],
    ["comment je transmets la fiche de securite", "securite-transmettre"],
    ["je veux voir les fiches de securite du mois dernier", "securite-periode"],
    ["chercher une fiche de securite d'un client", "securite-chercher"],
    ["comment j'envoie une fiche de chantier au client", "paysage-fiche"],
    ["faire la fiche d'hier", "fiche-chantier-autre-jour"],
    ["changer le client sur la fiche de chantier", "fiche-chantier-client"],
    ["envoyer la fiche par mail au lieu du sms", "fiche-chantier-sms-email"],
    ["cacher le temps passe au client", "fiche-chantier-temps"],
    ["renvoyer le lien de la fiche au client", "fiche-chantier-renvoyer"],
    ["supprimer une fiche brouillon", "fiche-chantier-supprimer"],
    ["reprendre une fiche commencee", "fiche-chantier-reprendre"],
    ["ou sont les rapports envoyes", "fiche-chantier-rapports-envoyes"],
    ["ou est composer ma fiche", "paysage-composer-ma-fiche"],
    ["ajouter une prestation sur ma fiche d'entretien", "composer-ajouter-prestation"],
    ["creer une nouvelle famille de prestations", "composer-ajouter-famille"],
    ["renommer une prestation de ma fiche", "composer-renommer"],
    ["enlever une prestation de ma fiche", "composer-retirer-prestation"],
    ["supprimer toute une famille", "composer-retirer-famille"],
    ["chercher un client", "clients-chercher"],
    ["comment je cree un client", "clients-creer"],
    ["changer le numero de telephone d'un client", "clients-modifier"],
    ["refaire le meme devis que l'an dernier", "clients-dernier-devis"],
    ["nouveau chantier pour un client que j'ai deja", "clients-autre-chantier"],
    ["qu'est ce qu'on lui a fait la derniere fois", "clients-derniere-prestation"],
    ["partager une facture par whatsapp", "clients-document"],
    ["supprimer un client", "clients-supprimer"],
    ["apprendre un mot a atlas", "catalogue-mots"],
    ["ou est le catalogue", "catalogue-ouvrir"],
    ["ajouter un materiel au catalogue", "catalogue-nouvelle-entree"],
    ["retirer un mot que j'ai ajoute", "catalogue-retirer-mot"],
    ["atlas me propose un mot, je fais quoi", "catalogue-mots-proposes"],
  ],
  reglages: [
    ["comment je crée mon compte", "arrivee-creer-compte"],
    ["je veux m'inscrire sur atlas", "arrivee-creer-compte"],
    ["j'ai pas reçu le code par mail", "arrivee-code-email"],
    ["comment je me connecte", "arrivee-se-connecter"],
    ["je peux me connecter avec google ?", "arrivee-google-apple"],
    ["entrer avec face id", "arrivee-face-id"],
    ["comment accepter les conditions pour entrer", "arrivee-documents-legaux"],
    ["comment je me déconnecte", "reglages-se-deconnecter"],
    ["quelle version j'ai", "reglages-version"],
    ["comment récupérer les dernières corrections", "reglages-chercher-corrections"],
    ["pourquoi mon salarié ne voit pas les tarifs", "reglages-reserve-patron"],
    ["comment ajouter un tarif", "reglages-tarifs"],
    ["supprimer un tarif", "reglages-tarifs"],
    ["importer mes prix depuis un fichier excel", "reglages-tarifs-importer"],
    ["remplir un prix dans la grille du dessouchage", "reglages-prix-case"],
    ["retirer un travail de la grille", "reglages-prix-retirer-travail"],
    ["ajouter une façon d'abattre au câble", "reglages-facon-abattre"],
    ["changer les tranches de diamètre", "reglages-mesures"],
    ["changer la forme juridique sasu", "reglages-forme-juridique"],
    ["où s'impriment les mentions légales", "reglages-mentions-legales"],
    ["je suis en franchise de tva", "reglages-regime-tva"],
    ["déclarer la tva tous les trimestres", "reglages-tva-rythme"],
    ["tva sur les encaissements ou les débits", "reglages-tva-exigibilite"],
    ["changer l'indicatif du téléphone", "reglages-telephone"],
    ["changer mon iban", "reglages-iban"],
    ["prévenir les clients de l'ancien iban", "reglages-iban-prevenir"],
    ["mettre mon assurance décennale", "reglages-decennale"],
    ["renseigner le médiateur de la consommation", "reglages-mediateur"],
    ["pourquoi il me redemande mon mot de passe", "reglages-preuve-mot-de-passe"],
    ["régler la validité du devis et l'acompte", "reglages-documents"],
    ["mettre virement et chèque comme moyens de paiement", "reglages-moyens-paiement"],
    ["afficher les pénalités de retard sur le devis", "reglages-penalites"],
    ["ajouter un texte en bas du devis", "reglages-texte-pied"],
    ["mettre mes conditions générales de vente", "reglages-cgv"],
    ["changer le message envoyé avec le devis", "reglages-message-client"],
    ["changer la numérotation des factures", "reglages-numero"],
    ["mettre mon logo sur le devis", "reglages-logo"],
    ["changer la couleur et la police du devis", "reglages-allure-couleurs"],
    ["donner un accès à un salarié", "reglages-donner-acces"],
    ["changer le rôle d'un salarié en facturation", "reglages-role"],
    ["limiter ce que le salarié voit du planning", "reglages-portee-planning"],
    ["retirer l'accès d'un salarié", "reglages-retirer-acces"],
    ["combien de chantiers par jour", "reglages-nombre-chantiers"],
    ["donner un nom à mes salariés", "reglages-salaries"],
    ["noter un congé d'un salarié", "reglages-absence"],
    ["exiger une photo en fin de chantier", "reglages-fin-chantier"],
    ["être relancé chaque semaine pour une facture impayée", "reglages-rappel-relance"],
    ["couper le rappel devis sans réponse", "reglages-rappel-couper"],
    ["relier mon agenda google", "reglages-agenda"],
    ["mettre en pause l'agenda", "reglages-agenda-pause"],
    ["relier mon agenda icloud", "reglages-agenda-apple"],
    ["mettre mes chantiers dans le calendrier de l'iphone", "reglages-agenda-apple-ecrire"],
    ["qu'est-ce que l'ia sait faire", "reglages-atlas-ia"],
    ["ajouter une règle pour l'ia", "vocabulaire-regles"],
    ["télécharger mes données", "reglages-donnees"],
    ["supprimer mon compte atlas", "reglages-effacer-compte"],
    ["résilier mon abonnement", "reglages-abonnement"],
    ["changer de formule d'abonnement", "reglages-formule"],
    ["changer mon prénom", "reglages-compte"],
    ["changer mon mot de passe", "reglages-mot-de-passe"],
    ["activer face id", "reglages-face-id"],
    ["retirer face id d'un ancien téléphone", "reglages-face-id-retirer"],
    ["j'ai perdu mon téléphone, me déconnecter partout", "reglages-deconnexion-partout"],
    ["passer en mode sombre", "reglages-apparence"],
    ["écrire une question à l'assistant", "assistant-ecrire"],
    ["poser ma question au micro", "assistant-dicter"],
    ["montrer une photo à l'assistant", "assistant-photo"],
    ["effacer la conversation de l'assistant", "assistant-oublier"],
    ["appliquer les modifications proposées", "assistant-propositions"],
    ["fermer l'assistant", "assistant-fermer"],
  ],
};
